oneMonthProject/Backend

build.gradle, src/main/java/com/example/demo/global/exception/customexception/TokenCustomException.java, src/main/java/com/example/demo/global/exception/errorcode/TokenErrorCode.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenDto.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenProvider.java, src/main/resources/application.properties
- JWT를 사용하기 위한 초기 셋팅 (의존성 추가, secret key 설정)
- JWT 로직을 담당하는 JsonWebTokenProvider 클래스 생성
- JsonWebTokenProvider에 토큰 발급, 토큰 검증, 토큰 추출 로직 구현
- Access Token과 Refresh Token을 함께 관리하는 JsonWebTokenDto 생성
=> [feature/74-jwt] JWT 로직 구현

src/main/java/com/example/demo/service/token/RefreshTokenRedisService.java
- Redis로 RefreshToken을 관리하기 위한 RefreshTokenRedisService 생성
- RefreshToken을 저장하는 save() 로직 구현, Redis에 key="refreshToken:회원PK", value="refreshToken" 형태로 저장하도록 구현
- RefreshToken을 조회하는 get() 로직 구현
- RefreshToken을 삭제하는 delete() 로직 구현
- RTR(Refresh Token Rotation) 기법을 사용하고자 RefreshToken을 수정하는 로직은 구현하지 않음
=> [feature/74-refresh-token-service] RefreshToken CRD 구현

src/main/java/com/example/demo/global/exception/customexception/TokenCustomException.java, src/main/java/com/example/demo/global/exception/errorcode/TokenErrorCode.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenProvider.java
- 토큰을 발급하는 로직 generateToken()의 파라미터 타입을 UserDetails -> PrincipalDetails로 변경
- AccessToken을 발급하는 과정에서 claims에 이메일과 닉네임 값을 추가로 셋팅해 발급받을 수 있도록 수정
- RefreshToken을 추출하는 로직 resolveRefreshToken()을 요청 헤더의 쿠키로부터 값을 추출하는 로직으로 변경
- 요청 헤더 쿠키에 RefreshToken 값이 존재하지 않을 경우의 에러코드, 커스텀 예외 추가
=> [feature/74-fix-jwt-provider] JWT Provider 수정

src/main/java/com/example/demo/dto/user/request/UserLoginRequestDto.java
- 로그인 로직을 수행 중 JsonWebTokenAuthenticationFilter의 attemptAuthentication() 메소드에서 request body 데이터를 읽어와 UserLoginRequestDto 타입으로 변환하는 과정에서 null이 담기는 버그가 발생해 UserLoginRequestDto에 기본 생성자를 추가하여 해결
=> [feature/74-fix-user-login-dto] 회원 로그인 요청 DTO 수정

src/main/java/com/example/demo/global/config/SecurityConfig.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenAuthorizationFilter.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenProvider.java
- JWT 검증 및 인가과정을 처리하는 JsonWebTokenAuthorizationFilter 구현
- 검증이 완료된 AccessToken에서 회원정보를 추출하여 시큐리티 사용자 인증 객체로 반환하는 로직 구현
- 인증 및 인가과정이 필요하지 않는 로직 중 "/api/user/login" 요청은 따로 동작하는 필터가 있어 해당 요청을 JsonWebTokenAuthorizationFilter 내에서 처리할 수 있도록 구현 (SecurityConfig의 configue(), filterChain()에서 처리하면 필터가 모든 요청에서 동작하는 이슈 발생)
=> [feature/74-security-jwt-authorization] JWT 검증 및 인가 로직 구현

src/main/java/com/example/demo/security/jwt/JsonWebTokenProvider.java
- JsonWebTokenProvider의 resolveAccessToken() 메소드 로직 수정
- Access Token 디코드 에러 이슈로 Access Token 값을 return 하는 코드에 .subString(7) 코드 추가해서 해결
=> [feature/74-fix-jwt-resolve-access-token] 요청 헤더에서 AccessToken 값 가져오는 로직 수정

src/main/java/com/example/demo/dto/user/response/UserCrewDetailResponseDto.java, src/main/java/com/example/demo/model/user/User.java, src/main/java/com/example/demo/repository/board/BoardRepositoryCustomImpl.java, src/main/java/com/example/demo/service/project/ProjectMemberFacade.java
- 신뢰점수, 신뢰등급 필드 삭제 (추후 변경가능 있음)
- 회원의 기술스택목록을 등록하는 메소드 생성
- 회원 엔티티를 수정함에 따라 관련 코드 임시 수정(UserCrewDetailResponseDto of(), BoardRepositoryCustomImpl getBoardSearchPage(), BoardFacade getCrewDetail())
=> [feature/74-fix-user-entity] 회원 엔티티 수정

src/main/java/com/example/demo/global/config/SecurityConfig.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenLogoutFilter.java
- 로그아웃 요청 시 동작하는 JsonWebTokenLogoutFilter 구현
- 시큐리티 필터체인에 등록하여 로그아웃 요청인 경우에만 JsonWebTokenLogoutFilter가 동작하도록 구현
- 시큐리티 컨텍스트에 저장되어 있는 현재 회원의 인증 정보 객체를 가져와 회원의 RefreshToken을 Redis에서 삭제하고, SecurityContextHolder.clearContext()를 통해 저장된 회원의 인증 정보를 삭제한 후 Response 객체에 RefreshToken 관련 쿠키를 초기화 시켜 응답하도록 로직 구현
#163
=> [feature/163-user-logout] 로그아웃 로직 구현

src/main/java/com/example/demo/security/SecurityResponseHandler.java
- 시큐리티 필터단에서 응답 처리를 공통으로 관리하기 위해 SecurityResponseHandler 클래스 구현
- SecurityResponseHandler 클래스를 스프링 빈으로 등록해 관리하고 sendResponse() 메소드를 통해 ResponseEntity를 생성하고 클라이언트에게 응답 객체를 전송하는 로직 구현
#163
=> [feature/163-security-filter-common-response] 시큐리티 필터단의 응답 처리를 공통으로 관리하기 위한 클래스 구현

src/main/java/com/example/demo/global/config/SecurityConfig.java, src/main/java/com/example/demo/security/custom/UserAuthenticationFailureHandler.java, src/main/java/com/example/demo/security/custom/UserAuthenticationSuccessHandler.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenExceptionFilter.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenLogoutFilter.java
- 필터 별 각자 응답 처리를 하던 방법에서 SecurityResponseHandler를 통해 공통으로 응답을 처리하도록 수정
- 각 필터에 SecurityResponseHandler 객체의 의존성을 주입해 sendResponse() 메서드를 통해 공통으로 클라이언트로 응답을 전송하도록 수정
- 각 필터의 로직이 수정됨에 따라 SecurityConfig의 내용도 수정
#163
=> [feature/163-fix-security-filter-response] 시큐리티 필터 응답 처리 수정

src/main/java/com/example/demo/security/custom/PrincipalDetails.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenProvider.java
- 회원 수정 시 변경될 수 있는 정보인 nickname, profileImgSrc 필드 PrincipalDetails에서 삭제
- PrincipalDetails 필드가 변경됨에 따라 JsonWebTokenProvider의 AccessToken을 생성하고, 토큰으로 회원의 인증 정보 객체를 반환하는 메소드 수정
=> [feature/fix-principal] PrincipalDetails 수정

src/main/java/com/example/demo/repository/user/UserTechnologyStackRepository.java, src/main/java/com/example/demo/service/user/UserTechnologyStackService.java, src/main/java/com/example/demo/service/user/UserTechnologyStackServiceImpl.java
- List<UserTechnologyStack>타입의 회원 기술스택 목록을 한번에 저장하는 로직 구현
- User 엔티티의 List<UserTechnologyStack> techStacks 필드 연쇄옵션 삭제 예정 (다대다 관계이기 때문에 연쇄 옵션을 사용하지 않고 직접 저장 및 삭제하고 셋팅하는 작업을 수행)
=> [feature/163-user-techstack-list-save] 회원 기술스택 목록 저장 로직 구현

src/main/java/com/example/demo/model/user/User.java
- 회원 엔티티의 List<UserTechnologyStack> 타입의 techStacks 필드의 OneToMany 연관관계 옵션 중 연쇄관련 cascade, orphanRemoval 옵션 삭제, UserTechnologyStack 엔티티는 다대다 관계의 중간 엔티티이기 때문에 연쇄 옵션을 삭제
- 회원 엔티티의 trustScore 필드에 fetch 타입을 명시하고 접근 제어자 private으로 수정
=> [feature/163-fix-user-entity] 회원 엔티티 수정

src/main/java/com/example/demo/controller/user/UserController.java, src/main/java/com/example/demo/dto/user/request/UserUpdateRequestDto.java, src/main/java/com/example/demo/dto/user/response/UserUpdateResponseDto.java, src/main/java/com/example/demo/model/user/User.java, src/main/java/com/example/demo/repository/user/UserRepositoryCustom.java, src/main/java/com/example/demo/repository/user/UserRepositoryImpl.java, src/main/java/com/example/demo/service/user/UserFacade.java, src/main/java/com/example/demo/service/user/UserService.java, src/main/java/com/example/demo/service/user/UserServiceImpl.java
- 회원 수정 요청 시 필요한 회원의 정보만 조회하는 로직을 queryDsl로 구현
- 클라이언트로부터 nickname, positionId, techStackIds, intro 4개의 수정 요청 데이터를 받고 positionId와 techStacksIds는 기존 회원의 정보와 비교하여 수정하도록 구현
- 회원 엔티티 영역에서 회원 기술스택을 삭제, 추가하는 로직과 회원 정보를 수정하는 로직 구현
- 수정된 데이터를 클라이언트로 응답하도록 구현
#163
=> [feature/163-user-update] 회원 수정 로직 구현

src/main/java/com/example/demo/service/user/UserFacade.java, src/main/java/com/example/demo/service/user/UserTechnologyStackService.java, src/main/java/com/example/demo/service/user/UserTechnologyStackServiceImpl.java
- UserFacade에서 회원 기술스택 조작관련 로직을 분리해서 UserTechnologyStackService에서 구현하고 UserFacade 클래스도 함께 수정
- UserTechnologyStackService의 저장, 삭제 로직을 비지니스 로직에 맞춰 수정(메소드명, 파라미터 타입, 로직)
- 회원 기술스택 엔티티와 회원 기술스택 목록을 생성하고 저장하는 로직을 분리
=> [feature/user-tech-stack-refactor] 회원 기술스택 조작 관련 로직 분리

src/main/java/com/example/demo/dto/user/response/UserProjectHistoryInfoResponseDto.java, src/main/java/com/example/demo/repository/user/UserProjectHistoryRepository.java, src/main/java/com/example/demo/repository/user/UserProjectHistoryRepositoryCustom.java, src/main/java/com/example/demo/repository/user/UserProjectHistoryRepositoryImpl.java, src/main/java/com/example/demo/service/user/UserProjectHistoryService.java, src/main/java/com/example/demo/service/user/UserProjectHistoryServiceImpl.java
- 회원 프로젝트 이력 정보를 응답하는 UserProjectHistoryInfoResponseDto 구현
- queryDsl을 활용해 회원 프로젝트 이력 갯수를 조회하는 쿼리 구현
- queryDsl을 활용해 회원 프로젝트 이력 목록을 페이징하여 조회하는 쿼리 구현, offset 방식을 사용하고 UserProjectHistoryInfoResponseDto 타입으로 데이터 응답
- UserProjectHistoryService에 회원 프로젝트 이력 갯수, 회원 프로젝트 이력 목록을 조회하는 로직 구현
=> [feature/get-user-project-history] 회원 프로젝트 이력 조회 로직 구현

src/main/java/com/example/demo/dto/user/request/UserTokenReissueRequestDto.java, src/main/java/com/example/demo/global/config/SecurityConfig.java, src/main/java/com/example/demo/global/exception/customexception/TokenCustomException.java, src/main/java/com/example/demo/global/exception/errorcode/TokenErrorCode.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenProvider.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenReissueFilter.java
- AccessToken이 만료되면 RefreshToken으로 새로운 AccessToken과 RefreshToken을 재발급하는 로직 구현 (RTR 적용)
- JsonWebTokenReissueFilter에 토큰을 재발급하는 로직을 구현해 필터단에서 처리되도록 구현
- 토큰 재발급을 위해서 회원의 ID(PK) 정보가 필요한데 AccessToken이 만료되면 AccessToken에서 회원 정보(ID(PK), email)를 추출할 수 없고, 현재 서비스에서는 RefreshToken에 회원 정보를 담고 있지 않기 때문에 클라이언트로부터 JSON 타입의 회원 ID(PK) 정보를 요청받도록 구현
- 토큰 재발급 요청 시, 클라이언트로부터 회원의 ID(PK)와 RefreshToken 정보를 요청받아 회원 검증과 RefreshToken 검증 절차를 수행하여 문제 발생 시 적절한 예외 처리를 진행하고 문제가 없을 경우 새로운 AccessToken과 RefreshToken을 발급해 토큰을 갱신하고 클라이언트에게 응답하도록 구현
#220
=> [feature/220-token-reissue] 토큰 재발급 로직 구현

src/main/java/com/example/demo/dto/user/response/UserMyInfoResponseDto.java, src/main/java/com/example/demo/service/user/UserFacade.java
- 회원의 프로젝트 이력 목록은 별도의 api 요청을 통해 조회하기로 결정하여 내 정보 조회 시 회원의 프로젝트 이력 목록을 함께 응답하지 않도록 변경
- UserMyInfoResponseDto에서 회원 프로젝트 이력 목록 필드 제거
=> [feature/fix-get-my-info] 내 정보 조회 로직 수정

src/main/java/com/example/demo/controller/board/BoardController.java, src/main/java/com/example/demo/global/exception/customexception/BoardCustomException.java, src/main/java/com/example/demo/global/exception/errorcode/BoardErrorCode.java, src/main/java/com/example/demo/model/board/Board.java, src/main/java/com/example/demo/service/board/BoardFacade.java
- 게시글 수정 로직에서 로그인한 회원의 인증 정보를 가져오기 위해 AuthenticationPricipal 어노테이션 등록
- Board 엔티티에 조작을 요청한 회원과 해당 게시글을 작성한 회원이 같은지 검증하는 로직 추가
- 만약 다른 경우 응답할 NO_PERMISSION_TO_EDIT_OR_DELETE 에러코드 및 커스텀 예외 추가
=> [feature/fix-update-board] 게시글 수정 로직 수정

src/main/java/com/example/demo/controller/board/BoardController.java, src/main/java/com/example/demo/service/board/BoardFacade.java, src/main/java/com/example/demo/service/board/BoardService.java, src/main/java/com/example/demo/service/board/BoardServiceImpl.java
- 게시글 삭제 로직에서 로그인한 회원의 인증 정보를 가져오기 위해 AuthenticationPricipal 어노테이션 등록
- 게시글 삭제 시 삭제를 요청한 회원을 검증하기 위해 BoardFacade에 게시글을 삭제하는 로직을 새로 구현
- BoardFacade의 deleteBoard() 로직을 통해 요청한 회원을 검증하고 검증이 완료된 후, 게시글을 삭제하도록 수정
=> [feature/fix-delete-board] 게시글 삭제 로직 수정

src/main/java/com/example/demo/controller/project/ProjectController.java, src/main/java/com/example/demo/service/project/ProjectFacade.java
- 프로젝트 참여 신청 수락 로직에서 로그인한 회원의 인증 정보를 가져오기 위해 AuthenticationPricipal 어노테이션 등록
- ProjectFacade 프로젝트 참여 신청 수락 메소드에 회원 ID(PK) 파라미터 추가
=> [feature/fix-project-participate-confirm] 프로젝트 참여 신청 수락 로직 수정

src/main/java/com/example/demo/global/config/SecurityConfig.java
- URI에서 각 도메인별 의미 전달을 명확하게 하기 위해 로그인 없이 접근이 가능한 요청의 URI 패턴을 기존 /api/public/** 에서 /**/public으로 변경
=> [feature/fix-security-authorization-uri-pattern] 인가 허용 URI 패턴 변경

src/main/java/com/example/demo/controller/board/BoardController.java, src/main/java/com/example/demo/controller/position/PositionController.java, src/main/java/com/example/demo/controller/technology_stack/TechnologyStackController.java, src/main/java/com/example/demo/controller/user/UserController.java, src/main/java/com/example/demo/security/custom/UserAuthenticationFilter.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenAuthenticationFilter.java
- 별도의 권한, 인증과정 없이 모든 접근이 허용된 URI 매핑 정보 수정
- 회원가입, 로그인, 이메일 중복확인, 닉네임 중복확인, 게시글 검색, 게시글 상세 조회, 직무 목록 조회, 기술스택 목록 조회 요청 URI 매핑 정보 뒤에 /public 추가
- JsonWebToken을 인증하는 로직에서 요청한 URI가 모든 접근이 허용된 URI 인지 확인하는 로직 수정
#240
=> [feature/240-fix-public-access] 모든 접근을 허용하는 URI 정보 수정

src/main/java/com/example/demo/dto/milestone/request/MileStoneUpdateRequestDto.java, src/main/java/com/example/demo/dto/milestone/request/MilestoneCreateRequestDto.java, src/main/java/com/example/demo/dto/milestone/request/MilestoneUpdateDateRequestDto.java, src/main/java/com/example/demo/dto/milestone/response/MilestoneCreateResponseDto.java, src/main/java/com/example/demo/dto/milestone/response/MilestoneReadResponseDto.java, src/main/java/com/example/demo/dto/project/request/ProjectCreateRequestDto.java, src/main/java/com/example/demo/dto/project/request/ProjectUpdateRequestDto.java, src/main/java/com/example/demo/dto/project/response/ProjectCreateResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectDetailResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectMeResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectSearchResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectSpecificDetailResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectUpdateResponseDto.java, src/main/java/com/example/demo/dto/work/request/WorkCreateRequestDto.java, src/main/java/com/example/demo/dto/work/request/WorkReadResponseDto.java, src/main/java/com/example/demo/dto/work/request/WorkUpdateRequestDto.java, src/main/java/com/example/demo/dto/work/response/WorkProjectDetailResponseDto.java, src/main/java/com/example/demo/model/milestone/Milestone.java, src/main/java/com/example/demo/model/project/Project.java, src/main/java/com/example/demo/model/user/UserProjectHistory.java, src/main/java/com/example/demo/model/work/Work.java, src/main/java/com/example/demo/service/user/UserProjectHistoryServiceImpl.java
- 요구사항 변경으로 기존 LocalDateTime 타입의 start_date, end_date 필드를 LocalDate 타입으로 변경
- 프로젝트, 마일스톤, 업무, 사용자 프로젝트 이력 엔티티의 start_date, end_date 타입 변경
- 각 엔티티의 start_date, end_date 타입 변경에 따라 관련 dto의 시작날짜, 종료날짜 필드 타입 변경
#240
=> [feature/240-fix-start-end-date-type] 시작날짜, 종료날짜 데이터 타입 변경

src/main/java/com/example/demo/dto/user/response/UserMyInfoResponseDto.java, src/main/java/com/example/demo/service/user/UserFacade.java
- 추후 직렬화로 공통된 날짜 데이터 응답을 처리하기 위해 내 정보 조회 응답 DTO에서 생성날짜, 수정날짜 필드의 타입을 String 타입에서 LocalDateTime 타입으로 수정
=> [feature/fix-user-get-myinfo] 내 정보 조회 로직 수정

src/main/java/com/example/demo/dto/alert/response/AlertInfoResponseDto.java, src/main/java/com/example/demo/dto/board/Response/BoardCreateResponseDto.java, src/main/java/com/example/demo/dto/board/Response/BoardDetailResponseDto.java, src/main/java/com/example/demo/dto/board/Response/BoardSearchResponseDto.java, src/main/java/com/example/demo/dto/board/Response/BoardUpdateResponseDto.java, src/main/java/com/example/demo/dto/milestone/response/MilestoneCreateResponseDto.java, src/main/java/com/example/demo/dto/milestone/response/MilestoneReadResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectCreateResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectDetailResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectMeResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectSpecificDetailResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectUpdateResponseDto.java, src/main/java/com/example/demo/dto/projectmember/response/ProjectMemberDetailResponseDto.java, src/main/java/com/example/demo/dto/projectmember/response/ProjectMemberReadProjectCrewsResponseDto.java, src/main/java/com/example/demo/dto/trust_score/ProjectUserHistoryDto.java, src/main/java/com/example/demo/dto/user/response/UserCrewDetailResponseDto.java, src/main/java/com/example/demo/dto/user/response/UserMyInfoResponseDto.java, src/main/java/com/example/demo/dto/work/response/WorkProjectDetailResponseDto.java
- 각 도메인별 응답 DTO에서 LocalDateTime 타입의 날짜 데이터 필드를 "yyyy-MM-dd" 형태로 응답하기 위한 JsonSerialize 어노테이션 직렬화 코드 추가
#240
=> [feature/240-response-dto-localdatetime-serialization] 응답 DTO LocalDateTime 타입 데이터 직렬화 설정

src/main/java/com/example/demo/controller/user/UserController.java, src/main/java/com/example/demo/dto/user/response/UserProjectHistoryInfoResponseDto.java, src/main/java/com/example/demo/repository/user/UserProjectHistoryRepositoryImpl.java, src/main/java/com/example/demo/service/user/UserFacade.java, src/main/java/com/example/demo/service/user/UserProjectHistoryServiceImpl.java
- 기존 int 타입의 pageNumber 데이터를 파라미터로 전달 받아 처리하던 로직에서 null 값에 대비해 Optional<Integer> 타입의 pageNumber 데이터를 전달 받도록 수정해 null인 경우 0번 페이지의 결과 값을 응답받도록 수정
- 요청할 수 있는 최소 페이지 번호를 1번에서 0번으로 변경하여 기존 요청한 페이지 번호 -1 한 값으로 페이징 처리를 수행하던 로직에서 요청한 페이지 번호만으로 페이징 처리를 수행하도록 수정
- 공통 형식의 날짜 데이터를 응답하기 위해 회원 프로젝트 이력 정보 DTO의 updateDate 필드의 타입을 변경하고 직렬화되도록 수정
- 기존 회원 프로젝트 이력을 조회하는 쿼리에서 MySQL의 DATE_FORMAT() 함수로 update_date 필드를 설정한 패턴의 String 타입으로 포맷해 응답 데이터를 셋팅하는 로직에서 LocalDateTime 타입의 update_date 정보를 그대로 가져와 응답 DTO단에서 직렬화를 통해 공통된 형식의 날짜 데이터를 응답하도록 수정
=> [feature/fix-user-get-my-projecthistorys] 내 프로젝트 이력 목록 조회 로직 수정

src/main/java/com/example/demo/global/config/SecurityConfig.java, src/main/java/com/example/demo/global/exception/errorcode/UserErrorCode.java, src/main/java/com/example/demo/security/custom/CustomAccessDeniedHandler.java
- 회원의 권한이 접근할 수 없는 권한인 경우 응답 할 커스텀 회원 에러코드 ACCESS_DENIED 추가
- 스프링 시큐리티에서 설정한 접근 권한에 대한 AccessDeniedException 발생 시 예외를 핸들링하고 처리 할 커스텀 핸들러 CustomAccessDeniedHandler 생성
- 요청한 회원의 권한을 확인하고, 해당 권한이 요청한 URI에 접근할 수 없는 경우 CustomAccessDeniedHandler가 동작하도록 시큐리티 필터체인에 커스텀 핸들러 등록
#240
=> [feature/240-custom-access-denied-handler] 접근 권한 예외처리 핸들러 생성

src/main/java/com/example/demo/dto/trust_score/ProjectUserHistoryDto.java, src/main/java/com/example/demo/dto/work/request/WorkCreateRequestDto.java, src/main/java/com/example/demo/dto/work/request/WorkReadResponseDto.java, src/main/java/com/example/demo/dto/work/response/WorkProjectDetailResponseDto.java, src/main/java/com/example/demo/global/validation/validator/AddPointDtoValidator.java, src/main/java/com/example/demo/model/work/Work.java, src/main/java/com/example/demo/repository/trust_score/TrustScoreHistoryRepositoryImpl.java, src/main/java/com/example/demo/repository/work/WorkRepository.java, src/main/java/com/example/demo/service/project/ProjectMemberFacade.java, src/main/java/com/example/demo/service/work/WorkService.java, src/main/java/com/example/demo/service/work/WorkServiceImpl.java, src/test/java/com/example/demo/trust_score/repository/TrustScoreHistoryRepositoryTest.java, src/test/java/com/example/demo/trust_score/service/TrustScoreServiceTest.java
- 기존 업무 엔티티의 expired_status, complete_status 두 개의 필드를 삭제하고 progress_status 필드 하나로 공통으로 관리하도록 수정
- 기존 업무 엔티티의 expired_status, complete_status 필드에 접근하고 조작하는 코드를 progress_status 필드로 변경하는 작업 수행
- 업무 생성 시, ProgressStatus.BEFORE_START(시작전) 정보가 저장되도록 수정
=> [feature/work-field-modify] 업무 엔티티 관련 필드 수정 및 리팩토링

src/main/java/com/example/demo/controller/work/WorkController.java, src/main/java/com/example/demo/dto/work/request/WorkUpdateRequestDto.java, src/main/java/com/example/demo/model/work/Work.java, src/main/java/com/example/demo/service/work/WorkFacade.java
- 기존 업무 엔티티의 progress_status 필드가 추가됨에 따라 업무 수정 요청 시 progress_status 정보도 수정할 수 있도록 WorkUpdateRequestDto에 progressStatusCode 필드 추가
- 기존 업무 엔티티의 수정 로직에 progress_status 정보와 마지막 수정한 프로젝트 구성원의 정보를 함께 수정할 수 있도록 변경
- 업무 수정 요청 시 사용자 정보를 가져올 수 있도록 AuthenticationPrincipal 어노테이션을 추가하여 요청한 사용자의 인증 정보를 파라미터로 받을 수 있도록 수정
=> [feature/fix-work-update] 업무 수정 로직 수정

src/main/java/com/example/demo/global/config/CorsConfig.java, src/main/java/com/example/demo/security/custom/UserAuthenticationSuccessHandler.java
chrome 80 정책으로 이제 sameSite 의 기본값이 "None"에서 "Lax" 로 변경되어 브라우저에 refresh token 이 저장되지 않았습니다.
cors 설정 및 cookie 에 sameSite 와 secure 설정 하였습니다.
=> feat: set same-site to refresh token

src/main/java/com/example/demo/global/config/CorsConfig.java
- 백엔드 로컬에서 배포된 서버 테스트를 위해 CorsConfig에 백엔드 로컬 호스트 추가
=> [feature/add-backend-local-server-origin] CorsConfig 백엔드 로컬 호스트 추가

src/main/java/com/example/demo/model/technology_stack/TechnologyStack.java, src/main/java/com/example/demo/model/technology_stack/TechnologyStackCategoryMapping.java
- 요구사항 변경으로 하나의 기술스택이 여러개의 기술스택 카테고리를 가질 수 있도록 수정하면서 기술스택 엔티티와 기술스택 카테고리 엔티티를 연결하는 TechnologyStackCategoryMapping 중간 엔티티 생성
- 기존 TechnologyStack 엔티티의 TechnologyStackCategory 필드를 삭제해 참조 관계를 끊고 중간 엔티티에서 관리하도록 수정 
#268
=> [feature/268-add-techstack-category-connect-entity] 기술스택 카테고리 매핑 엔티티 추가

src/main/java/com/example/demo/dto/work/request/WorkUpdateRequestDto.java, src/main/java/com/example/demo/model/work/Work.java, src/main/java/com/example/demo/service/work/WorkFacade.java
- 요구사항 변경으로 업무 수정 시 업무에 할당된 회원을 함께 수정하도록 로직 수정
- 업무 수정 요청 DTO WorkUpdateRequestDto에 Long 타입의 assignUserId 필드를 추가해 클라이언트로부터 변경하고자하는 프로젝트의 멤버 ID(PK) 값을 함께 요청 받아 할당된 회원을 함께 수정할 수 있도록 수정
close #286
=> [feature/286-fix-work-update] 업무 수정 로직 수정

src/main/java/com/example/demo/controller/work/WorkController.java, src/main/java/com/example/demo/dto/work/response/WorkPaginationResponseDto.java, src/main/java/com/example/demo/dto/work/response/WorkReadResponseDto.java, src/main/java/com/example/demo/global/exception/customexception/PageNationCustomException.java, src/main/java/com/example/demo/global/exception/errorcode/PageNationErrorCode.java, src/main/java/com/example/demo/repository/work/WorkRepository.java, src/main/java/com/example/demo/repository/work/WorkRepositoryCustom.java, src/main/java/com/example/demo/repository/work/WorkRepositoryImpl.java, src/main/java/com/example/demo/service/work/WorkFacade.java, src/main/java/com/example/demo/service/work/WorkService.java, src/main/java/com/example/demo/service/work/WorkServiceImpl.java
- 요구사항 변경으로 기존 프로젝트 > 마일스톤 > 업무 목록을 조회하는 로직에 페이징 작업 추가
- WorkRepositoryCustom, WorkRepositoryImpl 커스텀 레파지토리를 생성하고 QueryDsl을 사용해 조건에 맞는 데이터들을 페이징 처리하고 응답하도록 로직 수정 (시작날짜 기준 오름차순 정렬, 최소 0번 pageIndex, 최대 8개의 itemCount)
- 요청 페이지 데이터 개수관련 에러코드 및 커스텀 예외 생성
close #290
=> [feature/290-fix-get-work-list] 프로젝트 > 마일스톤 > 업무 목록 조회 로직 수정

src/main/java/com/example/demo/controller/project/ProjectController.java, src/main/java/com/example/demo/dto/project/response/ProjectPaginationResponseDto.java, src/main/java/com/example/demo/repository/user/UserProjectHistoryRepositoryCustom.java, src/main/java/com/example/demo/repository/user/UserProjectHistoryRepositoryImpl.java, src/main/java/com/example/demo/service/project/ProjectFacade.java, src/main/java/com/example/demo/service/user/UserProjectHistoryService.java, src/main/java/com/example/demo/service/user/UserProjectHistoryServiceImpl.java
- 요구사항 변경으로 요청한 회원이 참여중인 프로젝트 목록을 조회하는 로직 구현
- 요청한 회원의 ID(PK), pageIndex, itemCount 값으로 해당 회원의 프로젝트 이력 중 참여중인 이력을 페이징 처리해 조회하고 해당 프로젝트들의 정보를 응답하도록 구현
- 페이징 처리한 프로젝트들의 정보를 담은 List 타입의 content, 해당 회원이 참여중인 총 프로젝트 개수를 담은 long 타입의 totalPages 데이터를 ProjectPaginationResponseDto로 응답
close #304
=> [feature/304-participating-my-project-list] 회원의 참여중인 프로젝트 목록을 조회하는 로직 구현

src/main/java/com/example/demo/controller/work/WorkController.java, src/main/java/com/example/demo/service/work/WorkFacade.java
- 업무 생성 시 요청한 회원의 인증 정보를 파라미터로 받도록 수정
- 업무 생성 시 업무 엔티티의 lastModifiedMember 정보를 요청한 회원 정보와 해당 프로젝트 정보로 조회해 저장하도록 수정 
- 업무 생성 요청 데이터 중 assignedUserId 데이터가 ProjectMember 엔티티의 ID(PK)로 요청하여 할당 사용자 정보를 저장하는 로직을 ProjectMember 엔티티의 User 엔티티 값을 저장하도록 수정
=> [feature/fix-create-work] 업무 생성 로직 수정

src/main/java/com/example/demo/controller/technology_stack/TechnologyStackCategoryMappingController.java, src/main/java/com/example/demo/dto/technology_stack/response/TechnologyStackWithCategoriesResponseDto.java, src/main/java/com/example/demo/repository/technology_stack/TechnologyStackCategoryMappingRepository.java, src/main/java/com/example/demo/repository/technology_stack/TechnologyStackCategoryMappingRepositoryCustom.java, src/main/java/com/example/demo/repository/technology_stack/TechnologyStackCategoryMappingRepositoryImpl.java, src/main/java/com/example/demo/service/technology_stack/TechnologyStackCategoryMappingService.java, src/main/java/com/example/demo/service/technology_stack/TechnologyStackCategoryMappingServiceImpl.java
- 기술스택과 기술스택 카테고리를 관리하는 TechnologyStackCategoryMapping 테이블에서 모든 기술스택 별 카테고리들을 함께 조회하는 로직 구현
- 하나의 기술스택 당 여러개의 카테고리를 가질 수 있어 모든 TechnologyStackCategoryMapping 데이터를 조회해technology_stack_id(기술스택 ID(PK))를 기준으로 그룹핑하고 기술스택 ID와 기술스택 이름, 해당 기술스택에 포함된 카테고리 목록을 List에 담아 TechnologyStackWithCategoriesResponse DTO로 응답하도록 구현
- 응답 값
```
"data": [
{
"techStackId": 20,
"techStackName": "ReactNative",
"categories": [
"백엔드"
]
},
{
"techStackId": 21,
"techStackName": "Unity",
"categories": [
"IOS",
"안드로이드"
]
},
{
"techStackId": 22,
"techStackName": "Flutter",
"categories": [
"IOS",
"안드로이드",
"기타"
]
}
]
```
close #268
=> [feature/268-categories-by-tech-stacks] 모든 기술스택 별 카테고리를 함께 조회하는 로직 구현

src/main/java/com/example/demo/dto/projectmember/response/ProjectMemberReadCrewDetailResponseDto.java, src/main/java/com/example/demo/service/project/ProjectMemberFacade.java
- 프론트단에서 사용자가 프로젝트 멤버의 권한 정보를 확인해야 하므로 기존 프로젝트 멤버 상세 조회 응답 시 Long 타입의 projectMemberAuthId 정보를 ProjectMemberAuthResponseDto 타입으로 응답하도록 변경하고 필드명 수정
- 프로젝트 멤버 상세 정보를 조회하는 로직에서 ProjectMemberAuthResponseDto 데이터를 셋팅하고 응답하도록 수정
- 프로젝트 멤버 신뢰점수를 고정된 값을 셋팅하는 코드 수정
close #287
=> [feature/287-fix-project-member-detail-response] 프로젝트 멤버 상세 조회 응답 데이터 수정

src/main/java/com/example/demo/controller/project/ProjectMemberController.java, src/main/java/com/example/demo/dto/projectmember/response/ProjectMemberWorkWithTrustScoreResponseDto.java, src/main/java/com/example/demo/dto/projectmember/response/ProjectMemberWorksPaginationResponseDto.java, src/main/java/com/example/demo/repository/work/WorkRepositoryCustom.java, src/main/java/com/example/demo/repository/work/WorkRepositoryImpl.java, src/main/java/com/example/demo/service/project/ProjectMemberFacade.java, src/main/java/com/example/demo/service/work/WorkService.java, src/main/java/com/example/demo/service/work/WorkServiceImpl.java
- 요구사항을 반영하여 특정 프로젝트의 프로젝트 크루 상세 정보 페이지에서 해당 프로젝트 크루의 업무 이력과 각 업무 별 신뢰점수 내역을 조회할 수 있는 로직 구현
- 요청한 프로젝트 크루 ID(PK) 값으로 해당 프로젝트 크루가 속한 프로젝트 정보, 프로젝트 크루의 회원 정보로 조건에 맞는 데이터를 조회하도록 구현
- 각 업무별 데이터를 ProjectMemberWorkWithTrustScoreResponseDto(업무내용, 업무 시작날짜, 업무 종료날짜, 업무 진행상태, 업무에서 부여받은 신뢰점수, 업무 신뢰점수 타입)에 셋팅하고 ProjectMemberWorksPaginationResponseDto으로 총 업무 개수와 함께 응답
- 업무의 상태가 '시작전', '진행중'인 경우 해당 업무에 대한 신뢰점수 내역이 존재하지 않기 때문에 응답 시 'point', 'point_type' 필드에 null 값을 응답
- pageIndex, itemCount 페이징 관련 요청 데이터를 받아 조건에 맞도록 페이징 작업을 처리
close #288
=> [feature/288-project-member-works-with-trust-score] 특정 프로젝트 멤버의 업무 이력과 업무 별 신뢰점수 내역 조회 로직 구현

src/main/java/com/example/demo/dto/user/response/UserProjectHistoryPaginationResponseDto.java, src/main/java/com/example/demo/repository/user/UserProjectHistoryRepositoryCustom.java, src/main/java/com/example/demo/repository/user/UserProjectHistoryRepositoryImpl.java, src/main/java/com/example/demo/service/user/UserFacade.java, src/main/java/com/example/demo/service/user/UserProjectHistoryService.java, src/main/java/com/example/demo/service/user/UserProjectHistoryServiceImpl.java
- 요구사항 변경으로 사용자 프로젝트 이력 목록 조회 시 페이징 처리된 프로젝트 이력 목록과 해당 사용자의 전체 프로젝트 이력 개수를 함께 조회하고 응답하도록 변경
```
"data": {
"content": [
{
"userProjectHistoryId": 73,
"status": "PARTICIPATING",
"projectName": "프로젝트 이름6",
"updateDate": "2024-01-02"
},
{
"userProjectHistoryId": 64,
"status": "PARTICIPATING",
"projectName": "프로젝트 이름5",
"updateDate": "2024-01-02"
},
{
"userProjectHistoryId": 55,
"status": "PARTICIPATING",
"projectName": "프로젝트 이름4",
"updateDate": "2024-01-02"
},
{
"userProjectHistoryId": 46,
"status": "PARTICIPATING",
"projectName": "프로젝트 이름3",
"updateDate": "2024-01-02"
},
{
"userProjectHistoryId": 37,
"status": "PARTICIPATING",
"projectName": "프로젝트 이름2",
"updateDate": "2024-01-02"
}
],
"totalPages": 6
}
```
close #314
=> [feature/314-fix-get-user-project-history-response] 회원 프로젝트 이력 목록 조회 시 응답 형태 수정

src/main/java/com/example/demo/dto/projectmember/response/ProjectMemberWorkWithTrustScoreResponseDto.java, src/main/java/com/example/demo/repository/work/WorkRepositoryImpl.java
- 요구사항 변경으로 프로젝트 멤버 업무 이력 및 업무 별 신뢰점수 내역을 조회하는 로직의 응답 데이터에 업무 ID(PK) 값 추가
```
"data": {
"content": [
{
"workId": 74,
"workContent": "프로젝트12 > 마일스톤21 > 업무 내용8",
"startDate": "2024-02-01",
"endDate": "2024-02-10",
"progressStatus": "진행중",
"point": null,
"point_type": null
},
{
"workId": 28,
"workContent": "프로젝트12 > 마일스톤21 > 업무 내용7",
"startDate": "2024-01-18",
"endDate": "2024-01-20",
"progressStatus": "완료",
"point": 20,
"point_type": "minus"
},
{
"workId": 27,
"workContent": "프로젝트12 > 마일스톤21 > 업무 내용6",
"startDate": "2024-01-13",
"endDate": "2024-01-17",
"progressStatus": "완료",
"point": 50,
"point_type": "plus"
}
],
"totalPages": 8
}
```
close #317
=> [feature/317-fix-project-member-works-with-trust-score] 프로젝트 멤버 업무 이력 및 업무 별 신뢰점수 내역 조회 응답 데이터 수정

src/main/java/com/example/demo/dto/alert/response/AlertInfoResponseDto.java, src/main/java/com/example/demo/service/alert/AlertFacade.java
- 요구사항 변경으로 알림 정보 중 포지션 정보를 응답할 때 AlertInfoResponseDto에서 PositionInfoResponse 형태의 positionId, positionName으로 응답하도록 수정
- AlertInfoResponseDto의 of() 정적 메소드에서 알림 엔티티의 포지션 엔티티를 파라미터로 받도록 수정
- AlertInfoResponseDto의 of() 정적 메소드로 AlertInfoResponseDto를 응답하는 모든 로직에 position 매개변수 추가
```
"data": [
{
"alertId": 1,
"projectId": 12,
"checkUserId": 1,
"sendUserId": 1,
"workId": null,
"milestoneId": null,
"position": {
"positionId": 2,
"positionName": "백엔드"
},
"content": "프로젝트 지원 테스트 알림",
"type": "WORK",
"createDate": "2024-01-05",
"updateDate": "2024-01-05"
}
]
```
close #296
=> [feature/296-fix-alert-info-response] 알림 응답 정보 수정

src/main/java/com/example/demo/dto/work/response/WorkAssignedUserInfoResponseDto.java, src/main/java/com/example/demo/dto/work/response/WorkReadResponseDto.java, src/main/java/com/example/demo/repository/work/WorkRepositoryImpl.java, src/main/java/com/example/demo/service/work/WorkFacade.java, src/main/java/com/example/demo/service/work/WorkServiceImpl.java
- 프로젝트 멤버 ID(PK), 닉네임을 응답하는 WorkAssignedUserInfoResponseDto 생성
- 요구사항 변경으로 업무 조회 시 할당된 회원 정보를 WorkAssignedUserInfoResponseDto 형태로 응답하도록 수정
```
EX >
"data": {
"content": [
{
"workId": 28,
"projectId": 12,
"milestoneId": 21,
"assignedUser": {
"projectMemberId": 19,
"nickname": "mmm123"
},
"lastModifiedMemberNickname": "mmm123",
"content": "프로젝트12 > 마일스톤21 > 업무 내용7",
"startDate": "2024-01-18",
"endDate": "2024-01-20",
"progressStatus": "완료"
},
{
"workId": 74,
"projectId": 12,
"milestoneId": 21,
"assignedUser": {
"projectMemberId": 19,
"nickname": "mmm123"
},
"lastModifiedMemberNickname": "mmm123",
"content": "프로젝트12 > 마일스톤21 > 업무 내용8",
"startDate": "2024-02-01",
"endDate": "2024-02-10",
"progressStatus": "진행중"
},
{
"workId": 81,
"projectId": 12,
"milestoneId": 21,
"assignedUser": { …
```
=> [feature/301-fix-work-read-response] 업무 조회 응답 데이터 수정

src/main/java/com/example/demo/controller/work/WorkController.java, src/main/java/com/example/demo/service/work/WorkFacade.java, src/main/java/com/example/demo/service/work/WorkService.java, src/main/java/com/example/demo/service/work/WorkServiceImpl.java
- 하나의 업무 조회 시 응답하는 WorkReadResponseDto가 변경됨에 따라 해당 로직에서 프로젝트 멤버 엔티티를 조회하는 로직을 수행하기 위해 WorkService -> WorkFacade 클래스 이동 및 로직 수정
=> [feature/fix-work-get-one] 하나의 업무 조회 로직 수정

src/main/java/com/example/demo/controller/alert/AlertController.java, src/main/java/com/example/demo/dto/alert/response/AlertInfoResponseDto.java, src/main/java/com/example/demo/dto/position/response/PositionInfoResponseDto.java, src/main/java/com/example/demo/repository/alert/AlertRepository.java, src/main/java/com/example/demo/repository/alert/AlertRepositoryCustom.java, src/main/java/com/example/demo/repository/alert/AlertRepositoryImpl.java, src/main/java/com/example/demo/service/alert/AlertFacade.java, src/main/java/com/example/demo/service/alert/AlertService.java, src/main/java/com/example/demo/service/alert/AlertServiceImpl.java
- 요구사항 변경으로 프로젝트 내 알림 목록 조회 요청에서 페이징 처리된 데이터 목록과 총 데이터 개수를 함께 응답하도록 로직 수정
- 요청한 프로젝트의 알림 목록을 createDate(생성날짜) 기준으로 최신순으로 정렬하고 클라이언트로부터 요청 받은 pageIndex(페이지 번호), itemCount(페이지에 보여줄 개수) 정보에 일치하는 데이터 목록을 응답하도록 수정 
- 총 4개의 데이터 중 pageIndex=0, itemCount=3 요청인 경우
```
"data": {
"content": [
{
"alertId": 5,
"projectId": 1,
"checkUserId": 1,
"sendUserId": 21,
"workId": null,
"milestoneId": null,
"position": null,
"content": "프로젝트 1 지원합니다~",
"type": "RECRUIT",
"createDate": "2024-01-20",
"updateDate": "2024-01-20"
},
{
"alertId": 4,
"projectId": 1,
"checkUserId": 1,
"sendUserId": 16,
"workId": null,
"milestoneId": null,
"position": {
"positionId": 1,
"positionName": "프론트엔드"
},
"content": "프로젝트 1 지원!!",
"type": "RECRUIT",
"createDate": "2024-01-14",
"updateDate": "2024-01-14"
},
{
"alertId": 3, …
```
=> [feature/322-fix-get-alerts-by-project] 프로젝트 내 알림 목록 조회 로직 수정

src/main/java/com/example/demo/controller/board/BoardController.java, src/main/java/com/example/demo/dto/board/Response/BoardCreateResponseDto.java, src/main/java/com/example/demo/dto/board/Response/BoardDetailResponseDto.java, src/main/java/com/example/demo/dto/board/Response/BoardSearchResponseDto.java, src/main/java/com/example/demo/dto/board/Response/BoardUpdateResponseDto.java, src/main/java/com/example/demo/model/board/Board.java, src/main/java/com/example/demo/service/board/BoardService.java, src/main/java/com/example/demo/service/board/BoardServiceImpl.java
- 게시글의 모집상태를 모집중 -> 모집완료, 모집완료 -> 모집중으로 변경하는 로직 구현
- 요청한 사용자와 게시글을 작성한 사용자를 비교해 검증에 실패할 경우 게시글을 수정/삭제할 수 있는 권한이 존재하지 않는다는 예외를 처리하도록 구현
close #324
=> [feature/324-board-update-recruitment-status] 게시글 모집상태 변경 api 구현

build.gradle, src/main/java/com/example/demo/controller/user/UserController.java, src/main/java/com/example/demo/global/config/AwsS3Config.java, src/main/java/com/example/demo/global/exception/GlobalExceptionHandler.java, src/main/java/com/example/demo/global/exception/customexception/FileCustomException.java, src/main/java/com/example/demo/global/exception/errorcode/FileErrorCode.java, src/main/java/com/example/demo/global/util/FileUtil.java, src/main/java/com/example/demo/model/user/User.java, src/main/java/com/example/demo/service/file/AwsS3FileService.java, src/main/java/com/example/demo/service/user/UserFacade.java, src/main/resources/application.properties
- 회원수정 로직에서 회원의 프로필 이미지도 함께 등록/변경할 수 있도록 수정, 회원수정 요청 시 파일 데이터를 요청받도록 수정
- 이미지 파일 저장을 위한 aws s3 버킷을 생성하고, 의존성을 추가해 생성한 aws s3 버킷과 연동
- application.properies에 aws s3 관련 설정 및 파일 관련 설정 추가 (파일의 최대 요청 가능한 크기를 5MB로 설정)
- 로컬환경에서 aws s3 접근 테스트를 위해 별도의 설정 필요(EC2에서 접근할 때는 필요없음)
```
1. 인텔리제이 Run(실행) 탭 클릭
2. 실행 탭에서 Edit Configurations(구성 편집) 탭 클릭
3. 구성 편집 창에서 VM Option에 "-Dcom.amazonaws.sdk.disableEc2Metadata=true" 추가
3-1. 만약 VM Option 칸이 존재하지 않는다면 Modify options(옵션 수정) 버튼 클릭 후, Add VM options(VM 옵션 추가) 클릭 후 위의 코드 추가
```
- 파일명 새로 구성, 로컬에 저장된 임시 파일 삭제, MultipartFile 타입을 File 타입으로 변환, 파일타입 검증 등 파일 관련 작업을 수행하는 FileUtil 클래스 추가
- aws s3 버킷에 실제 파일을 업로드, 다운로드, 조회, 삭제 역할을 담당하는 AwsS3FileService 추가 및 업로드 로직 구현
- 회원수정 시 요청한 파일 데이터가 있는 경우, 해당 파일을 업로드하고 회원의 프로필 이미지 경로를 수정하도록 로직 수정
#331
=> [feature/331-add-user-profile-img] 회원 프로필 이미지 등록/변경 로직 추가

src/main/java/com/example/demo/service/user/UserFacade.java
- 파일 데이터를 요청하지 않아도 프로필 이미지 등록 조건을 실행하는 버그 수정
```
// 수정 전
if(Objects.nonNull(file)) {
....
}
// 수정 후
if(Objects.nonNull(file) && !file.isEmpty()) {
....
}
```
- 요청한 파일 데이터가 존재할 때, 프로필 이미지를 등록/변경 하기 전 이미 프로필 이미지가 존재하는 회원인 경우 기존 이미지 파일을 삭제하도록 로직 수정
=> [feature/fix-update-user-profile-img] 회원수정 로직에서 프로필 이미지 관련 로직 수정

src/main/java/com/example/demo/controller/user/UserController.java
- 회원수정 api의 MultipartFile 타입의 파일 데이터 required 속성을 false로 수정
- 회원수정 요청 시 파일 데이터는 null 값을 요청할 수 있는데 클라이언트에서 form-data 타입으로 데이터를 요청할 때 null 값을 셋팅할 수 없어 파일 데이터를 요청받을 때 requried 속성을 false로 설정
=> [feature/fix-update-user-multipartfile-attribute] 회원수정 api 파일 데이터 속성 수정

src/main/java/com/example/demo/global/exception/customexception/AuthenticationCustomException.java, src/main/java/com/example/demo/security/custom/PrincipalDetailsService.java, src/main/java/com/example/demo/security/custom/UserAuthenticationFailureHandler.java, src/main/java/com/example/demo/security/custom/UserAuthenticationFilter.java
```
org.springframework.security.authentication.InternalAuthenticationServiceException: null
at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:109) ~[spring-security-core-5.7.11.jar:5.7.11]	
.....
.....
Caused by: com.example.demo.global.exception.customexception.UserCustomException: null
at com.example.demo.global.exception.customexception.UserCustomException.<clinit>(UserCustomException.java:19) ~[main/:na]
at com.example.demo.security.custom.PrincipalDetailsService.lambda$loadUserByUsername$0(PrincipalDetailsService.java:25) ~[main/:na]
at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
at com.example.demo.security.custom.PrincipalDetailsService.loadUserByUsername(PrincipalDetailsService.java:25) …
```
=> [feature/fix-authentication-exception] 인증 예외처리 수정

src/main/java/com/example/demo/controller/user/UserController.java, src/main/java/com/example/demo/model/user/User.java, src/main/java/com/example/demo/service/user/UserFacade.java
- 서비스 내 회원 탈퇴를 요청하는 로직 구현
- 회원 탈퇴 요청 시 로그인한 회원(요청한 회원)의 ID(PK) 값으로 회원 정보를 조회하고 해당 회원의 status 필드를 UserStatus.DELETED 값으로 변경하는 논리적 삭제 방법으로 구현 (추후 다양한 방법을 찾아 개선할 예정)
close #331
=> [feature/331-user-withdraw] 회원 탈퇴 로직 구현

Dockerfile
- 배포 시 ec2에서 애플리케이션 도커 컨테이너가 자동으로 실행되지 않는 버그 발생으로 빌드된 jar 파일을 /app 디렉토리에 복사했기 때문에 Dockerfile ENTRYPOINT의 jar 파일 경로에 /app 경로를 추가해 올바르게 참조하도록 수정
=> [feature/fix-dockerfile] Dockerfile 수정

src/main/java/com/example/demo/controller/project/ProjectController.java, src/main/java/com/example/demo/dto/project/request/ProjectConfirmRequestDto.java, src/main/java/com/example/demo/global/exception/customexception/ProjectCustomException.java, src/main/java/com/example/demo/global/exception/errorcode/ProjectErrorCode.java, src/main/java/com/example/demo/model/alert/Alert.java, src/main/java/com/example/demo/service/project/ProjectFacade.java
- 기존 프로젝트 참여지원 수락 api를 수락 또는 거절로 다르게 처리되도록 로직 수정
- 프로젝트 참여 컨펌 api 요청 데이터 수정
```
{
"alertId": Long,            # 해당 지원 알림의 ID(PK)
"confirmResult": boolean    # 프로젝트 참여 컨펌 여부, 수락(true)/거절(false)
}
```
- api를 요청한 회원이 프로젝트 참여 컨펌을 수행할 수 있는지 검증하기 위한 에러코드 및 커스텀 예외 추가
- Alert 엔티티에 프로젝트 참여지원 시 컨펌 결과를 저장하기 위해 Boolean 타입의 project_participate_confirm 필드 추가
- Alert 엔티티에 프로젝트 참여지원 결과를 update 하기 위한 메소드 구현
- 프로젝트 참여 수락 시, 지원 알림 엔티티의 project_participate_confirm 필드를 true로 업데이트하고 새로운 프로젝트 합류 알림 생성
- 프로젝트 참여 거절 시, 지원 알림 엔티티의 project_participate_confirm 필드를 false로 업데이트
- 프로젝트 합류 알림을 생성할 때 null 값을 셋팅하기 위해 Alert 엔티티의 check_user_id 필드의 nullable=false 속성 제거
#332
=> [feature/332-fix-project-participate-confirm] 프로젝트 참여지원 컨펌 로직 수정

src/main/java/com/example/demo/controller/alert/AlertController.java, src/main/java/com/example/demo/dto/alert/response/AlertSupportedProjectInfoResponseDto.java, src/main/java/com/example/demo/dto/project/response/ProjectSimpleInfoResponseDto.java, src/main/java/com/example/demo/repository/alert/AlertRepositoryCustom.java, src/main/java/com/example/demo/repository/alert/AlertRepositoryImpl.java, src/main/java/com/example/demo/service/alert/AlertFacade.java, src/main/java/com/example/demo/service/alert/AlertService.java, src/main/java/com/example/demo/service/alert/AlertServiceImpl.java
- 사용자가 지원한 프로젝트에 대한 결과(수락/거절)를 확인하기 위한 알림목록 조회 로직 구현
- 프로젝트의 ID, Name 을 응답하는 ProjectSimpleInfoResponseDto 및 지원한 프로젝트 관련 알림 데이터를 응답하는 AlertSupportedProjectInfoResponseDto 생성
- 기존 전체 알림 데이터의 개수를 카운트하는 로직을 동적으로 처리하도록 변경 (BooleanBuilder로 상황에 맞는 쿼리가 동작하도록 수정)
- 조회한 결과 데이터 페이징 및 정렬 처리
- 예상 응답 값
```
"data": {
"content": [
{
"project": {
"projectId": 1,
"projectName": "프로젝트 이름 1"
},
"position": {
"positionId": 3,
"positionName": "안드로이드"
},
"supportResult": false
},
{
"project": {
"projectId": 26,
"projectName": "프로젝트명 1"
},
"position": {
"positionId": 3,
"positionName": "안드로이드"
},
"supportResult": true
},
{
"project": {
"projectId": 27,
"projectName": "trustcrew"
},
"position": {
"positionId": 3,
"positionName": "안드로이드"
},
"supportResult": false
}
],
"totalPages": 3
}
```
close #350
=> [feature/350-supported-project-alerts-by-user] 사용자가 지원한 프로젝트 관련 알림목록 조회 로직 구현

src/main/java/com/example/demo/dto/user/response/UserProjectHistoryInfoResponseDto.java, src/main/java/com/example/demo/repository/user/UserProjectHistoryRepositoryImpl.java
사용자 프로젝트 이력에서 해당 프로젝트를 클릭하면 그 프로젝트로 이동해야하는 부분이 있는데, 
여태 userProjectHistoryId 가 projectId 인 줄  알고  연결하고 있었습니다.. 
오류를 확인 하였는데 요청 드리기엔 제가 이번주 다음주에 시간이 별로 없어서 수정했습니다.
approve 해주시면 제가 merge 하겠습니다.
=> feat: add projectId in UserProjectHistoryInfoResponseDto

src/main/java/com/example/demo/repository/user/UserProjectHistoryRepositoryCustom.java, src/main/java/com/example/demo/repository/user/UserProjectHistoryRepositoryImpl.java, src/main/java/com/example/demo/service/project/ProjectFacade.java, src/main/java/com/example/demo/service/user/UserFacade.java, src/main/java/com/example/demo/service/user/UserProjectHistoryService.java, src/main/java/com/example/demo/service/user/UserProjectHistoryServiceImpl.java
- 회원의 참여중인 프로젝트 이력 목록을 조회할 때 데이터가 중복되고 조건에 일치하는 데이터가 포함되지 않는 버그가 발생해 조회 쿼리 로직 수정
- 회원의 프로젝트 이력 목록 갯수를 조회하는 쿼리를 하나의 쿼리에서 조건에 따라 동적 쿼리로 처리되도록 변경
=> [feature/fix-user-participate-projects] 회원의 참여중인 프로젝트 이력 목록 조회 로직 수정

src/main/java/com/example/demo/controller/work/WorkController.java, src/main/java/com/example/demo/dto/work/request/WorkConfirmRequestDto.java, src/main/java/com/example/demo/global/exception/customexception/WorkCustomException.java, src/main/java/com/example/demo/global/exception/errorcode/WorkErrorCode.java, src/main/java/com/example/demo/global/validation/validator/AddPointDtoValidator.java, src/main/java/com/example/demo/service/work/WorkFacade.java
- 업무 완료 및 기간만료 시 해당 업무에 대한 신뢰점수를 부여/차감 처리를 수행하는 컨펌 로직 구현
- 업무 완료 및 기간만료 시 발송되는 업무 관련 알림 정보와 scoreTypeId(부여/차감) 정보로 해당 업무가 포함된 프로젝트의 등급과 scoreTypeId 정보에 따라 각각의 신뢰점수를 부여 및 차감하도록 구현
```
{
"alertId": Long,
"scoreTypeId": Long(1 or 2)
}
```
<br>
- 요청한 사용자가 업무 컨펌 작업을 수행할 수 있는 사용자인지 검증하는 로직과 에러코드 및 커스텀 예외 추가
- 기존 신뢰점수 부여 및 차감 로직에서 사용하는 AddPointDto를 검증하는 aop에서 업무 관련 검증 조건 수정, 업무의 미완수 조건을 progress_status가 'COMPLETION' 혹은 'EXPIRED'가 아닌 경우로 수정
<br><br><br>
close #332
=> [feature/332-project-work-alert-confirm] 업무 컨펌 로직 구현

build.gradle
- 프로젝트 빌드 시 `javax.annotation.meta.When not found` 경고 발생, 해당 경고는 `@Nullable` 어노테이션 when 속성에 대한 값을 처리하지 못해 발생
- 경고를 해결하기 위해 build.gradle에 JSR305 의존성 추가
`implementation 'com.google.code.findbugs:jsr305:3.0.2'`
- 추후 해당 경고에 대한 자세한 원인 및 어떻게 처리할 수 있는지 추가 확인
<br><br><br>
close #341
=> [feature/341-build-warning] 빌드 경고 해결

src/main/java/com/example/demo/service/project/ProjectMemberFacade.java, src/main/java/com/example/demo/service/work/WorkServiceImpl.java
- 기존 프로젝트의 멤버 목록을 조회하는 로직에서 각 멤버의 마지막에 완료한 작업 정보가 없는 경우 orElseThrow()로 예외를 처리하여 제대로된 정보를 응답하지 못하는 이슈 해결
- 해당 멤버가 마지막에 완료한 작업이 없는 경우 예외를 처리하지 않고 orElse(null)로 null을 반환하고 DTO의 값을 셋팅할 때 null인 경우 null 값을 응답하도록 수정
- 업무가 없는 경우
`"lastWorkDate": null`
- 업무가 존재하는 경우
`"lastWorkDate": "2024-01-30"`
<br><br><br>
close #361
=> [feature/361-fix-projectmembers-by-project] 프로젝트 멤버 목록 조회 로직 수정

src/main/java/com/example/demo/constant/ProjectRole.java, src/main/java/com/example/demo/global/exception/customexception/ProjectMemberAuthCustomException.java, src/main/java/com/example/demo/global/exception/errorcode/ProjectMemberAuthErrorCode.java, src/main/java/com/example/demo/service/project/ProjectFacade.java, src/main/java/com/example/demo/service/project/ProjectMemberService.java, src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java, src/main/java/com/example/demo/service/work/WorkFacade.java
- 프로젝트 역할, 권한이 매니저인지 검증하는 로직 구현
- 요청한 사용자의 해당 프로젝트 역할, 권한을 비교 및 검증하기 위한 ProjectRole enum 파일 생성
- 프로젝트 매니저 검증 로직에서 매니저가 아닐 경우, `INSUFFICIENT_PROJECT_AUTH(HttpStatus.FORBIDDEN, "해당 작업을 처리할 프로젝트 권한이 부족합니다.")` 커스텀 예외를 처리하도록 구현
- 기존 프로젝트 참여 지원 컨펌 로직과 업무 컨펌로직에 프로젝트 매니저 검증 로직 추가, 추후 탈퇴 컨펌 로직에도 수정 후 추가 예정
<br><br><br>
close #360
=> [feature/360-verified-project-manager] 프로젝트 매니저 검증 로직 구현

src/main/java/com/example/demo/controller/project/ProjectMemberController.java, src/main/java/com/example/demo/dto/project/request/ProjectWithdrawConfirmRequestDto.java, src/main/java/com/example/demo/service/project/ProjectMemberFacade.java, src/main/java/com/example/demo/service/project/ProjectMemberService.java, src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java
- 기존 프로젝트 멤버 탈퇴 컨펌 로직을 삭제하고 새로운 로직 구현
- API 엔드포인트를 `/api/projectmember/withdraw/confirm` 으로 변경하고 project_member_id 정보는 받지않도록 수정
- Long 타입의 alertId, boolean 타입의 withdrawConfirm 데이터를 Request Body로 요청받아 프로젝트 탈퇴 컨펌 로직 수행하도록 구현
- 프로젝트 탈퇴 컨펌 수락 시 project_member 엔티티를 삭제하고 해당 멤버가 프로젝트를 탈퇴했다는 확인 알림 생성
=> [feature/fix-project-withdraw-confirm] 프로젝트 탈퇴 컨펌 로직 수정

src/main/java/com/example/demo/dto/user/response/UserCrewDetailResponseDto.java
- 프로젝트 멤버 상세조회 로직에서 회원의 닉네임 값에 이메일이 셋팅되어 응답되는 버그 수정, 닉네임 값이 셋팅되도록 수정<br><br><br>
close #365
=> [feature/365-fix-projectmember-detail-response] 프로젝트 멤버 상세조회 응답값 수정

src/main/java/com/example/demo/controller/project/ProjectMemberController.java, src/main/java/com/example/demo/service/project/ProjectMemberFacade.java
- 프로젝트 탈퇴 신청 로직에 요청받은 projectMemberId 값으로 멤버를 조회하고 해당 멤버의 회원 정보와 요청한 회원 정보를 비교, 검증하는 로직 추가
- 프로젝트 탈퇴 신청 알림 생성 시 지원/모집 알림 값으로 셋팅하는 버그 수정
=> [feature/fix-project-withdraw]프로젝트 탈퇴 신청, 알림 전송 로직 수정

src/main/java/com/example/demo/dto/alert/request/AlertCreateRequestDto.java, src/main/java/com/example/demo/model/alert/Alert.java, src/main/java/com/example/demo/service/alert/AlertFacade.java
- 알림 엔티티 sendUser 필드에 null 값을 허용하도록 nullable 속성 제거
- 알림 생성 요청 DTO에서 checkUserId, sendUserId 필드가 null 값을 허용하도록 `@NotNull` 어노테이션 제거
- 알림 생성 로직에서 checkUserId, sendUserId 필드가 null 값을 허용하므로 null 체크 로직 추가 및 수정<br><br><br>
close #366
=> [feature/366-alert-nullable] 알림 엔티티 null 관련 작업

src/main/java/com/example/demo/service/alert/AlertFacade.java
- 클라이언트로부터 sendUserd 정보는 project_member_id 데이터로 요청받아 알림 전송 로직에서 project_member_id의 프로젝트 멤버를 조회하고 해당 멤버의 회원 정보를 sendUser에 셋팅하도록 수정
=> [feature/fix-alert-send] 알림 전송 로직 sendUser 데이터 셋팅 수정

src/main/java/com/example/demo/controller/alert/AlertController.java, src/main/java/com/example/demo/repository/alert/AlertRepositoryCustom.java, src/main/java/com/example/demo/repository/alert/AlertRepositoryImpl.java, src/main/java/com/example/demo/service/alert/AlertFacade.java, src/main/java/com/example/demo/service/alert/AlertService.java, src/main/java/com/example/demo/service/alert/AlertServiceImpl.java
- `/api/alert/project/{projectId}/recruits`: 프로젝트 모집알림 목록 조회
- `/api/alert/project/{projectId}/works`: 프로젝트 업무 알림목록 조회
- `/api/alert/project/{projectId}/crews`: 프로젝트 크루 알림목록 조회
- 위의 3가지 로직을 특정 프로젝트의 전체 알림 목록을 조회하는 api인 `/api/alert/project/{projectId}`와 동일하게 페이징과 정렬을 적용해 데이터 목록을 응답하도록 수정
- 기존 프로젝트 알림 목록 조회 쿼리를 함께 공유하기 위해 로직 수정
- 동적 조건 쿼리를 추가해 각 조건에 맞는 데이터 목록을 하나의 쿼리 메소드에서 조회하도록 수정
- 각 조건별 알림 데이터 개수를 조회하기 위해 기존 프로젝트 알림 목록 조회 쿼리에서 알림 데이터 개수를 조회하는 로직을 분리하고 public 메소드로 변경하여 service layer에서 각 조건별로 호출할 수 있도록 변경
- 요청한 페이징 관련 데이터를 검증하는 공통 로직을 따로 메소드화해서 분리
<br><br><br>
close #381
=> [feature/381-fix-get-alerts-by-condition] 각 조건별 알림 목록 조회 로직 수정

src/main/java/com/example/demo/dto/alert/response/AlertSupportedProjectInfoResponseDto.java
- 기존 사용자가 지원한 프로젝트 알림목록 조회 시 응답하는 AlertSupprotedProjectInfoResponse DTO에서 참여지원 결과 데이터 supportResult 필드의 타입을 null 값도 응답하기 위해 boolean -> Boolean 타입으로 변경
=> [feature/fix-user-supproted-projects] 사용자가 지원한 프로젝트 일림목록 조회 수정

src/main/java/com/example/demo/dto/alert/response/AlertSupportedProjectInfoResponseDto.java, src/main/java/com/example/demo/repository/alert/AlertRepositoryImpl.java
- 사용자가 참여지원한 프로젝트에 대한 알림목록을 조회하는 로직의 응답 값에 해당 알림의 ID(PK) 값 추가
- 사용자가 참여지원한 프로젝트 알림목록 조회 쿼리에 해당 알림 데이터의 ID(PK) 값을 AlertSupportedProjectInfoResponse DTO에 함께 셋팅하도록 수정
=> [feature/fix-user-participate-supported-project-alerts-response] 사용자가 참여지원한 프로젝트 알림 목록 조회 응답값 수정

src/main/java/com/example/demo/controller/alert/AlertController.java, src/main/java/com/example/demo/model/alert/Alert.java, src/main/java/com/example/demo/repository/alert/AlertRepository.java, src/main/java/com/example/demo/service/alert/AlertService.java, src/main/java/com/example/demo/service/alert/AlertServiceImpl.java
- 기존 알림 확인상태를 true(확인)로 변경하는 로직에 `@Transactional` 어노테이션이 없어 발생한 오류 해결
- 기존 Repository에서 요청한 알림 데이터의 확인상태 수정 작업을 처리하던 방법에서 Alert 엔티티에서 처리하도록 updateCheckedStatusIsTrue() 메소드 추가
- 알림 확인상태 변경 api의 HttpMethod를 `PutMapping` -> `PatchMapping`으로 변경<br><br><br>
close #389
=> [feature/389-fix-alert-check-status-update] 알림 확인상태 변경 로직 버그 해결 및 로직 수정

src/main/java/com/example/demo/dto/alert/response/AlertInfoResponseDto.java, src/main/java/com/example/demo/repository/alert/AlertRepositoryImpl.java
- 알림 정보 응답 데이터에 boolean 타입의 알림 확인 여부 `checkedStatus` 필드 추가
- 알림 정보를 조회하는 쿼리에서 Alert 엔티티의 checked_YN 필드를 조회 및 셋팅하도록 수정<br><br><br>
close #392
=> [feature/392-fix-alerts-info-response] 알림 정보 응답 수정

src/main/java/com/example/demo/controller/project/ProjectController.java, src/main/java/com/example/demo/model/project/Project.java, src/main/java/com/example/demo/repository/alert/AlertRepository.java, src/main/java/com/example/demo/repository/milestone/MileStoneRepository.java, src/main/java/com/example/demo/repository/work/WorkRepository.java, src/main/java/com/example/demo/service/alert/AlertService.java, src/main/java/com/example/demo/service/alert/AlertServiceImpl.java, src/main/java/com/example/demo/service/milestone/MilestoneService.java, src/main/java/com/example/demo/service/milestone/MilestoneServiceImpl.java, src/main/java/com/example/demo/service/project/ProjectFacade.java, src/main/java/com/example/demo/service/project/ProjectService.java, src/main/java/com/example/demo/service/project/ProjectServiceImpl.java, src/main/java/com/example/demo/service/work/WorkService.java, src/main/java/com/example/demo/service/work/WorkServiceImpl.java
- 프로젝트 종료 요청 시 로직 수정
- 요청한 회원의 userId, 요청한 projectId로 해당 프로젝트의 역할, 권한 검증(매니저)
- 해당 프로젝트 멤버 별 사용자 프로젝트 이력 데이터에 프로젝트 완주 이력 추가
- 해당 프로젝트의 멤버, 기술스택, 업무, 마일스톤, 알림 데이터 삭제
- 해당 프로젝트의 status 필드를 'FINISH'로 변경
- 프로젝트 엔티티에 모든 멤버를 삭제하는 로직 추가
- 프로젝트 엔티티에 모든 기술스택을 삭제하는 로직 추가
#396
=> [feature/396-fix-project-end] 프로젝트 종료 로직 수정

src/main/java/com/example/demo/controller/project/ProjectMemberController.java, src/main/java/com/example/demo/model/project/Project.java, src/main/java/com/example/demo/service/project/ProjectMemberFacade.java, src/main/java/com/example/demo/service/project/ProjectMemberService.java, src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java
- 프로젝트 멤버 강제탈퇴 요청 시 로직 수정
- 로그인한 회원, 프로젝트 멤버의 프로젝트 정보로 요청한 회원의 프로젝트 역할, 권한 매니저 검증
- 사용자 프로젝트 이력에 프로젝트 강제탈퇴 이력 추가
- 해당 프로젝트에서 해당 멤버 제거
- 프로젝트 멤버 강제탈퇴 api 엔드포인트 수정
- `/api/projectmember/{projectMemberId}/force-withdrawal`
- 프로젝트 멤버 강제탈퇴 컨트롤러 메소드명 오타 수정
=> [feature/fix-project-member-forced-withdrawal] 프로젝트 멤버 강제탈퇴 로직 수정

src/main/java/com/example/demo/controller/project/ProjectController.java, src/main/java/com/example/demo/repository/project/ProjectMemberRepository.java, src/main/java/com/example/demo/service/project/ProjectFacade.java, src/main/java/com/example/demo/service/project/ProjectMemberService.java, src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java
참여중인 프로젝트 목록 조회 로직을 수정했습니다. 
기존에는 프로젝트 이력 테이블과 프로젝트 테이블을 매핑했는데, 프로젝트 이력이 추가 되는 방식이 바뀌면서 (status만 업데이트 -> 새로 이력 추가) 프로젝트 이력 테이블의 status값만으로는 실제로 참여중인 프로젝트만 조회할 수가 없어서 수정했습니다. 
**소면님이 기존에 작성하셨던 서비스 로직은 그대로 남겨두고, 제가 새로 만든 서비스 로직 컨트롤러단에서 호출하게 했어요.** 
jpa는 써보지 않아서 기존 코드 참고해가면서 작업한거라 동작할지는 테스트해봐야 알 것 같아요. 
코드상에 문제되는 것 없으면  배포 부탁드려요.
=> feat: 참여중인 프로젝트 목록 조회 로직 수정: userId로 프로젝트 멤버 조회 -> 프로젝트 조회

src/main/java/com/example/demo/controller/project/ProjectController.java, src/main/java/com/example/demo/dto/project/request/ProjectInfoUpdateRequestDto.java, src/main/java/com/example/demo/model/project/Project.java, src/main/java/com/example/demo/service/project/ProjectFacade.java
- 프로젝트 정보 수정 요청 로직 구현
- 요청한 회원이 해당 프로젝트의 매니저인지 검증
- 요청한 수정 데이터로 프로젝트 정보 수정
- 예상 요청 값
```
{
"projectId": Long
"projectName": "String",
"subject": "String"
"trustGradeId": Long, #신뢰등급 ID(1~4)
"startDate": "yyyy-MM-dd"
"endDate": "yyyy-MM-dd"
}
```
- 예상 응답 값
```
{
"result": "success",
"message": "프로젝트 정보 수정이 완료되었습니다.",
"data": null
}
```
<br><br><br>
close #396
=> [feature/396-project-update] 프로젝트 정보 수정 로직 구현

build.gradle, src/main/java/com/example/demo/constant/OAuthProvider.java, src/main/java/com/example/demo/dto/oauth2/response/OAuth2InfoResponseDto.java, src/main/java/com/example/demo/global/config/SecurityConfig.java, src/main/java/com/example/demo/global/exception/customexception/OAuth2CustomException.java, src/main/java/com/example/demo/global/exception/errorcode/OAuth2ErrorCode.java, src/main/java/com/example/demo/global/util/CookieUtils.java, src/main/java/com/example/demo/model/user/User.java, src/main/java/com/example/demo/repository/user/UserRepository.java, src/main/java/com/example/demo/security/jwt/JsonWebTokenProvider.java, src/main/java/com/example/demo/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java, src/main/java/com/example/demo/security/oauth2/handler/OAuth2AuthenticationFailureHandler.java, src/main/java/com/example/demo/security/oauth2/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/example/demo/security/oauth2/service/OAuth2PrincipalDetails.java, src/main/java/com/example/demo/security/oauth2/service/OAuth2PrincipalService.java, src/main/java/com/example/demo/security/oauth2/user/OAuth2UserInfo.java, src/main/java/com/example/demo/security/oauth2/user/OAuth2UserInfoFactory.java
- OAuth 회원을 구분하기 위한 User 엔티티에  oAuthProvider, oAuthProviderId 필드 추가
- 소셜 로그인을 위한 스프링 시큐리티 OAuth2 적용
- `OAuthProvider` : OAuth 제공자를 enum으로 관리하기 위한 클래스
- `OAuth2UserInfo` : OAuth2 서버로부터 제공 받은 사용자 정보를 관리하기 위한 인터페이스
- `OAuth2UserInfoFactory` : 각 OAuth2 제공자 별로 OAuth2UserInfo 객체를 생성하기 위한 클래스
- `OAuth2PrincipalDetails` : 스프링 시큐리티의 OAuth2User, UserDetails를 구현한 커스텀 OAuth2 인증 객체
- `OAuth2PrincipalService` : 엑세스 토큰을 OAuth2 제공자로부터 제공 받았을 때 실행하는 서비스 클래스, 스프링 시큐리티의 DefaultOAuth2UserService 클래스를 상속받아 OAuth2 인증 과정을 수행하고 해당 소셜 회원의 서비스 등록 여부에 따라 다른 인증 객체를 반환
- `OAuth2AuthenticationSuccessHandler`/`OAuth2AuthenticationFailureHandler` : OAuth2 인증 과정에 성공 및 실패 시 실행되는 핸들러, 성공 시 서비스에 가입되지 않은 회원인 경우 OAuth 제공자 정보와 OAuth 고유번호를 응답하고 가입된 회원인 경우 서비스 자체 JWT 발급
- `HttpCookieOAuth2AuthorizationRequestRepository` : OAuth2 …
=> [feature/386-security-oauth2] 스프링 시큐리티 OAuth2 적용

src/main/java/com/example/demo/security/oauth2/user/KakaoOAuth2UserInfo.java, src/main/java/com/example/demo/security/oauth2/user/OAuth2UserInfoFactory.java, src/main/resources/application.properties
- 카카오 서버로부터 제공 받은 사용자 정보를 관리하는 클래스 KakaoOAuth2UserInfo 클래스 추가
- 요청한 OAuth2 제공자별 OAuth2UserInfo 객체를 반환하는 로직에 카카오 추가
- 시큐리티 OAuth2 카카오 설정 추가<br><br><br>
#386
=> [feature/386-oauth-kakao] OAuth 카카오 추가

src/main/java/com/example/demo/service/project/ProjectFacade.java
- 기존 참여중인 프로젝트 목록 조회 로직에서 특정 프로젝트의 멤버 목록 중 탈퇴, 강제탈퇴한 멤버도 함께 응답되는 버그 해결
- 특정 프로젝트의 멤버정보를 응답 DTO로 변환하는 로직에서 filter() 메소드를 활용해 참여중인 멤버들만 응답되도록 수정<br><br><br>
close #413
=> [feature/413-participate-project-members] 참여중인 프로젝트 목록 조회 시 특정 프로젝트 멤버 데이터 응답 수정

src/main/java/com/example/demo/repository/board/BoardRepositoryCustom.java, src/main/java/com/example/demo/repository/board/BoardRepositoryCustomImpl.java, src/main/java/com/example/demo/service/board/BoardServiceImpl.java
- 기존 게시글 목록 검색 조회 시 모집이 만료된 게시글 및 게시글의 프로젝트가 종료된 목록까지 함께 조회되는 버그 해결
- 게시글 목록 검색 조회 시 특정 게시글의 모집상태(recruitmentStatus) 값이 false(모집중)이고 게시글의 프로젝트 상태 값(projectStatus)이 'FINISH'가 아닌 게시글 목록만을 조회하도록 수정
<br><br><br>
close #415
=> [feature/415-fix-board-search] 게시글 목록 검색 조회 로직 수정

src/main/java/com/example/demo/controller/work/WorkController.java, src/main/java/com/example/demo/dto/projectmember/response/ProjectMemberWorkWithTrustScoreResponseDto.java, src/main/java/com/example/demo/dto/work/request/WorkCreateRequestDto.java, src/main/java/com/example/demo/dto/work/request/WorkUpdateRequestDto.java, src/main/java/com/example/demo/dto/work/response/WorkProjectDetailResponseDto.java, src/main/java/com/example/demo/dto/work/response/WorkReadResponseDto.java, src/main/java/com/example/demo/model/work/Work.java, src/main/java/com/example/demo/repository/work/WorkRepositoryImpl.java
- Work 엔티티에 업무 상세내용 contentDetail 필드 추가
- 업무 관련 로직 수행 시 새로 추가한 contentDetail 필드 요청, 응답 추가
- `WorkCreateRequestDto` : 업무 생성 요청 데이터에 contentDetail 값 추가
- `WorkUpdateRequestDto` : 업무 수정 요청 데이터에 contentDetail 값 추가
- `WorkReadResponseDto`, `WorkProjectDetailResponseDto`, `ProjectMemberWorkWithTrustScoreResponseDto` : 업무 관련 응답 데이터에 contentDetail 값 추가
- 업무 목록 관련 조회 쿼리에서 Work 엔티티의 contentDetail 값을 셋팅하도록 수정<br><br><br>
close #417
=> [feature/417-fix-work] 프로젝트 업무 관련 수정

src/main/java/com/example/demo/controller/user/UserController.java, src/main/java/com/example/demo/dto/oauth2/request/OAuth2UserCreateRequestDto.java, src/main/java/com/example/demo/global/exception/customexception/UserCustomException.java, src/main/java/com/example/demo/global/exception/errorcode/UserErrorCode.java, src/main/java/com/example/demo/repository/user/UserRepository.java, src/main/java/com/example/demo/service/user/UserFacade.java, src/main/java/com/example/demo/service/user/UserService.java, src/main/java/com/example/demo/service/user/UserServiceImpl.java
- 소셜 로그인 후 서비스에 가입되지 않은 회원인 경우 서비스 회원가입을 위한 OAuth 회원가입 로직 구현
- 클라이언트로부터 oAuthProvider(OAuth 제공자), oAuthProviderId(OAuth 고유번호), nickname, positionId, techStackIds, intro 요청
- 소셜 회원가입은 일반 회원가입과 동일하지만 email, password 값을 요청, 저장하지 않고 OAuth 제공자 정보와 OAuth 고유번호 정보를 저장 
- 요청받은 OAuth 제공자 정보와 OAuth 고유번호로 이미 가입된 회원인지 검증하는 로직 및 커스텀 예외, 에러코드 추가<br><br><br>
#386
=> [feature/386-oauth-signup] OAuth 소셜 회원가입 로직 구현

src/main/java/com/example/demo/model/user/User.java, src/main/java/com/example/demo/service/user/UserFacade.java
- User 엔티티 생성 시 또는 User 엔티티의 techStacks 필드에 데이터 추가 및 삭제 시 자동으로 UserTechnologyStack 테이블에도 반영되도록 하기 위해 User 엔티티의 회원 기술스택 목록을 저장하는 techStacks 필드에 `orphanRemoval = true`, `cascade = CascadeType.PERSIST` 옵션 추가
- User 엔티티에 해당 회원의 모든 기술스택 목록을 제거하는 메소드 구현
- 회원가입, 소셜 회원가입, 회원수정, 회원탈퇴 로직에서 User의 TechStack 추가 및 삭제하는 로직 코드 수정
=> [enhancement/modify-user-techstacks-cascade] User 엔티티 techStacks 필드 수정 (속성 추가)

src/main/java/com/example/demo/controller/work/WorkController.java, src/main/java/com/example/demo/repository/alert/AlertRepository.java, src/main/java/com/example/demo/service/alert/AlertService.java, src/main/java/com/example/demo/service/alert/AlertServiceImpl.java, src/main/java/com/example/demo/service/work/WorkFacade.java, src/main/java/com/example/demo/service/work/WorkService.java, src/main/java/com/example/demo/service/work/WorkServiceImpl.java
- 기존 업무 삭제 요청 시 해당 업무 정보를 가진 알림 데이터가 존재하는 경우 삭제되지 않고 오류가 발생하는 버그 해결
- 업무 삭제 요청 시 요청한 회원 정보를 추가로 받아 요청한 회원이 업무가 속한 프로젝트의 멤버인지 검증하고 해당 업무를 삭제하기 전 해당 업무 정보를 가진 알림 데이터 목록을 함께 삭제하도록 로직 새로 구현<br><br><br>
close #422
=> [bugfix/422-work-delete] 업무 삭제 요청 시 버그 수정

src/main/java/com/example/demo/dto/trust_score/AddPointDto.java, src/main/java/com/example/demo/model/trust_score/TrustScoreHistory.java, src/test/java/com/example/demo/service/trust_score/AddPointTest.java
- TrustScoreHistory 엔티티에 신뢰점수 내용 content 필드 추가 (ex. 회원가입, 업무 완료, 업무 만료, 프로젝트 멤버 탈퇴 등)
- 신뢰점수 부여, 차감 요청 시 필요한 AddPointDto에 content 필드 추가
- AddPointDto 테스트 코드 수정, 생성자 content 필드에 빈 값("") 셋팅
=> [feature/add-field-trust-score-history] 신뢰점수 이력 엔티티에 새로운 필드 추가

src/main/java/com/example/demo/service/work/WorkFacade.java
- 업무 컨펌 로직에서 해당 업무 상태에 따른 신뢰점수 부여 시 content 필드도 함께 셋팅하도록 수정
- 신뢰점수 이력 content 필드에 `업무 내용` + `특정 업무 신뢰점수 타입` 형태로 저장하도록 구현
- 특정 업무 신뢰점수 타입
- 업무 상태가 `COMPLETION(완료)` AND 요청 scoreType이 `+(1)`인 경우 -> `완수`
- 업무 상태가 `COMPLETION(완료)` AND 요청 scoreType이 `-(2)`인 경우 -> `미흡`
- 업무 상태가 `EXPIRED(기간만료)` -> `만료`
=> [feature/fix-work-confirm-trust-score-history] 업무 컨펌 로직에서 신뢰점수 이력 관련 로직 수정

src/main/java/com/example/demo/dto/projectmember/response/ProjectMemberWorkWithTrustScoreResponseDto.java, src/main/java/com/example/demo/repository/trust_score/TrustScoreHistoryRepositoryCustom.java, src/main/java/com/example/demo/repository/trust_score/TrustScoreHistoryRepositoryImpl.java, src/main/java/com/example/demo/repository/work/WorkRepositoryCustom.java, src/main/java/com/example/demo/repository/work/WorkRepositoryImpl.java, src/main/java/com/example/demo/service/project/ProjectMemberFacade.java, src/main/java/com/example/demo/service/trust_score/TrustScoreHistoryService.java, src/main/java/com/example/demo/service/trust_score/TrustScoreHistoryServiceImpl.java, src/main/java/com/example/demo/service/work/WorkService.java, src/main/java/com/example/demo/service/work/WorkServiceImpl.java
- 기존 프로젝트 멤버의 업무와 해당 업무의 신뢰점수 이력 목록을 불러오는 로직에서 만약 특정 업무가 삭제된 경우 삭제된 업무의 신뢰점수 이력을 조회하지 못하는 버그 수정
- 기존 로직을 삭제하고 삭제된 업무를 대비해 Work 테이블에서 조회하지 않고 TrustScoreHistory 테이블에서 work_id 필드가 null이 아니고 특정 프로젝트 멤버의 프로젝트 정보, 회원 정보와 일치하는 신뢰점수 이력 목록을 조회하는 로직 새로 구현
- 해당 요청의 응답 값으로 TrustScoreHistoryId, workContent(TrustScoreHistory의 content 필드), point, point_type, createDate 데이터를 응답하도록 수정
```
"data": {
"content": [
{
"trustScoreHistoryId": 317,
"workContent": "업무 테스트 완수",
"point": 20,
"point_type": "plus",
"createDate": "2024-02-20"
}
],
"totalPages": 1
}
```
<br><br><br>
close #425
=> [feature/425-fix-project-member-work-history] 프로젝트 멤버의 업무 + 신뢰 이력 조회 로직 수정

src/main/java/com/example/demo/global/validation/validator/AddPointDtoValidator.java, src/main/java/com/example/demo/service/project/ProjectMemberFacade.java
- 프로젝트 멤버 강제탈퇴 로직에 강제탈퇴에 따른 해당 멤버의 신뢰점수를 차감하는 로직 추가
- 신뢰점수 부여 및 차감 DTO AddPointDto 검증 로직 중 프로젝트 멤버 탈퇴, 강제탈퇴 로직 수정
- 요청한 프로젝트 멤버가 없는 경우, 요청한 프로젝트 멤버의 상태가 참여중이 아닌 경우 검증 실패하도록 수정
=> [feature/fix-project-member-force-withdrawal] 프로젝트 멤버 강제탈퇴 로직 수정

src/main/java/com/example/demo/global/config/SecurityConfig.java
- 시큐리티 제외 경로에 아이콘 관련 브라우저가 자동으로 요청하는 정적 자원(리소스)에 대한 `/favicon.ico` 경로 추가
- 해당 요청 시 스프링 시큐리티 필터체인의 JWT 인증 부분에서 예외를 응답하는 버그 수정
=> [feature/exclude-security-path] 시큐리티 제외 경로 추가

src/main/java/com/example/demo/model/alert/Alert.java, src/main/java/com/example/demo/model/project/ProjectMember.java
- Alert 엔티티 AlertType Enum 타입의 type 필드, ProjectMember 엔티티 ProjectMemberStatus 타입의 status 필드에 `@Enumerated(value = EnumType.String)` 를 적용해 String 타입으로 관리하도록 수정, 모든 엔티티의 Enum 필드 공통화
-Enum 데이터에서 값을 삭제하거나 새로운 값을 추가할 경우, 기존 Enum 데이터들의 인덱스 정보에 영향을 끼쳐 오류가 발생하는 문제를 해결하기 위해 Database에 Enum 데이터를 저장 시 인덱스가 아닌 String 타입으로 저장되도록 수정
=> [feature/fix-entity-enum-field] 엔티티 Enum Type의 필드 수정

src/main/java/com/example/demo/constant/AlertType.java, src/main/java/com/example/demo/repository/alert/AlertRepository.java, src/main/java/com/example/demo/repository/alert/AlertRepositoryImpl.java, src/main/java/com/example/demo/service/project/ProjectMemberFacade.java
- AlertType Enum 파일의 탈퇴, 강제탈퇴 오타 수정
- `WITHDRAWL` -> `WITHDRAWAL`
- `FORCEDWITHDRAWL` -> `FORCED_WITHDRAWAL`
- AlertType Enum 파일에서 탈퇴, 강제탈퇴 데이터를 참조해 사용하는 로직 수정(쿼리 조건문, 알림 엔티티 생성)
=> [fix/enum-typo-alert-type] 알림타입 Enum 데이터 오타 수정

src/main/java/com/example/demo/controller/user/UserController.java
- 사용자 정보 조회 요청 URL 경로에서 `/user` 패턴이 중복되는 이슈 해결
- `/api/user/user/{userId}` -> `/api/user/{userId}`
=> [fix/user-info-url] 사용자 정보 조회 요청 URL 경로 수정

src/main/java/com/example/demo/service/project/ProjectMemberAuthServiceImpl.java
- 기존 특정 프로젝트 멤버 권한 ID의 프로젝트 멤버 권한을 조회하는 서비스 구현체 로직에서 1L의 고정 값이 셋팅되어 있는 버그 수정
- 파라미터로 받은 Long 타입의 id 필드를 findById() 메소드의 매개변수로 셋팅
=> [fix/find-project-member-auth-by-id] 특정 프로젝트 멤버 권한 조회 수정

src/main/java/com/example/demo/service/board/BoardPositionService.java, src/main/java/com/example/demo/service/board/BoardService.java, src/main/java/com/example/demo/service/milestone/MilestoneService.java, src/main/java/com/example/demo/service/position/PositionService.java, src/main/java/com/example/demo/service/project/ProjectMemberAuthService.java, src/main/java/com/example/demo/service/project/ProjectService.java, src/main/java/com/example/demo/service/project/ProjectTechnologyService.java
- 인터페이스 추상 메소드에 명시적으로 설정해놓은 'public' 접근 제어자 삭제
- 추상 메소드의 구현부(인터페이스 멤버)와 접근 제어자 중복 경고 문제 해결
=> [remove/abstract-method-access-modifiers-warning] 추상 메소드 접근제어자 제거 & 중복 경고 해결

src/main/java/com/example/demo/repository/alert/AlertRepositoryCustom.java, src/main/java/com/example/demo/repository/alert/AlertRepositoryImpl.java
- AlertRepositoryCustom, AlertRepositoryImpl에서 알림 목록의 개수를 카운트하는 쿼리의 반환 타입을 long -> Long 타입으로 수정
- 기존 long 타입을 반환하는 경우 만약 특정 조건의 데이터가 존재하지 않으면 NullPointException을 발생시킨다는 경고 문제 해결, Long 타입을 반환하여 없는 경우 null 값을 반환하도록 수정
=> [fix/count-query-return-type-warning] 데이터 개수 카운트 쿼리 반환 타입 수정 및 경고 해결

docker-compose.yml
- docker 엔진과의 호환성을 위해 docker-compose 버전을 3 -> 3.8 버전으로 변경
=> fix : docker-compose 버전 수정

.github/workflows/deploy-cicd.yml
- cicd 워크 플로우 push 이벤트 실행 브랜치를 develop으로 수정
-
=> fix : cicd push 이벤트 발생 브랜치 변경

.github/workflows/deploy-cicd.yml
- 기존 베포 환경에서 도커로 스프링부트 서버를 실행하고 AWS ElastiCache로 Reids를 실행하는 방법에서 도커 컴포즈로 스프링부트와 레디스를 함께 실행하도록 수정
-
=> fix : 도커 컴포즈를 통해 스프링부트와 레디스를 함께 실행하도록 배포 스크립트 수정
