oneMonthProject/Backend

src/main/java/com/example/demo/repository/AlertRepository.java
src/main/java/com/example/demo/repository/BoardPositionRepository.java
src/main/java/com/example/demo/repository/BoardRepository.java
src/main/java/com/example/demo/repository/MileStoneRepository.java
src/main/java/com/example/demo/repository/ProjectMemberAuthRepository.java
src/main/java/com/example/demo/repository/ProjectMemberRepository.java
src/main/java/com/example/demo/repository/ProjectRepository.java
src/main/java/com/example/demo/repository/TrustGradeRepository.java
src/main/java/com/example/demo/repository/UserProjectHistoryRepository.java
src/main/java/com/example/demo/repository/WorkRepository.java

[Feature/3-create-boardProject-dto] 리포지토리 작성

---

src/main/java/com/example/demo/dto/Board/Request/BoardCreateRequestDto.java
src/main/java/com/example/demo/dto/BoardProject/Request/BoardProjectCreateRequestDto.java
src/main/java/com/example/demo/dto/Project/Request/ProjectCreateRequestDto.java

BoardProjectCreateRequestDto, BoardCreateRequestDto, ProjectCreateRequestDto추가

[feature-3-create-boardProject-dto]  게시글 생성 DTO 추가

---

src/main/java/com/example/demo/dto/Board/Request/BoardSearchRequestDto.java

[feature-3-create-boardSearch-dto] 게시글 목록 조회 REQUEST DTO 개발

---

build.gradle
src/main/java/com/example/demo/config/QueryDslConfig.java

querydslConfig 설정, build.gradle 설정 추가

[feature-3-create-querydsl-Config] querydslConfig 설정, build.gradle 설정 추가

---

src/main/java/com/example/demo/dto/Common/ResponseDto.java

[feature/3-create-responsedto] Common에 responsedto 개발

---

src/main/java/com/example/demo/dto/position/response/PositionInfoResponseDto.java

- 직무(position) 관련 DTO 패키지 설계
- 직무 정보를 응답하는 PositionInfoResponseDto 생성

[feature/6-position-dto-design] 직무 DTO 설계

---

src/main/java/com/example/demo/dto/technology_stack/response/TechnologyStackInfoResponseDto.java

- 기술스택(technology_stack) 관련 DTO 패키지 설계
- 기술스택 정보를 응답하는 TechnologyStackInfoResponseDto 생성

[feature/6-techstack-dto-design] 기술스택 DTO 설계

---

src/main/java/com/example/demo/dto/user/request/UserCreateRequestDto.java
src/main/java/com/example/demo/dto/user/request/UserLoginRequestDto.java
src/main/java/com/example/demo/dto/user/request/UserUpdateRequestDto.java
src/main/java/com/example/demo/dto/user/response/UserInfoResponseDto.java
src/main/java/com/example/demo/dto/user/response/UserTokenInfoResponseDto.java

- 회원 생성 요청 DTO UserCreateRequestDto 구현
- 회원 로그인 요청 DTO UserLoginRequestDto 구현
- 회원 수정 요청 DTO UserUpdateRequestDto 구현
- 회원 정보 응답 DTO UserInfoResponseDto 구현
- 회원 토큰 정보 응답 DTO UserTokenInfoResponseDto 구현

[feature/6-user-dto-design] 회원 DTO 설계

---

src/main/java/com/example/demo/dto/board_project/request/BoardProjectCreateRequestDto.java
src/main/java/com/example/demo/dto/project/request/ProjectCreateRequestDto.java

ProjectCreateRequestDto 없어져서 추가

[feature/20-create-board-project-request-dto] ProjectCreateRequestDto 없어져서 추가

---

src/main/java/com/example/demo/dto/project/response/ProjectUpdateResponseDto.java

ProjectUpdateResponseDto 추가 올렸는데 빠짐

[feature/20-project-update-response-dto] ProjectUpdateResponseDto 추가

---

src/main/java/com/example/demo/dto/project/response/ProjectUpdateResponseDto.java

[feature/20-project-update-response-dto] import 수정

---

src/main/java/com/example/demo/dto/board/Response/BoardCreateResponseDto.java
src/main/java/com/example/demo/dto/board_project/response/BoardProjectCreateResponseDto.java
src/main/java/com/example/demo/dto/project/response/ProjectCreateResponseDto.java

[Feature/3-create-board-project-response-dto] BoardProjectResponsedto 개발

---

src/main/java/com/example/demo/dto/board/Response/BoardCreateResponseDto.java
src/main/java/com/example/demo/dto/board_project/response/BoardProjectCreateResponseDto.java

[feature/3-create-board-controller] import 변경

---

build.gradle
src/main/java/com/example/demo/global/config/RedisConfig.java
src/main/resources/application.properties

- Redis 사용을 위한 dependency 추가
- RedisConfig 클래스 생성 및 초기 설정

[feature/25-redis-config] Redis 설정

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/dto/board/Response/BoardSearchResponseDto.java
src/main/java/com/example/demo/dto/project/response/ProjectSearchResponseDto.java
src/main/java/com/example/demo/dto/trust_grade/response/TrustGradeResponseDto.java
src/main/java/com/example/demo/dto/user/response/UserSearchResponseDto.java

BoardSearchResponseDto, ProjectSearchResponseDto, TrustGradeResponseDto, UserSearchResponseDto 개발

[feature/3-create-board-controller] 검색 부분 컨트롤러, DTO 개발

---

src/main/java/com/example/demo/global/exception/customexception/PositionCustomException.java
src/main/java/com/example/demo/repository/board/BoardRepository.java
src/main/java/com/example/demo/repository/board/BoardRepositoryCustom.java
src/main/java/com/example/demo/repository/board/BoardRepositoryCustomImpl.java
src/main/java/com/example/demo/service/board/BoardService.java

Feature/3 create board controller 게시글 검색 개발

---

src/main/java/com/example/demo/controller/user/UserController.java
src/main/java/com/example/demo/global/exception/customexception/UserCustomException.java
src/main/java/com/example/demo/global/exception/errorcode/UserErrorCode.java
src/main/java/com/example/demo/repository/user/UserRepository.java
src/main/java/com/example/demo/service/user/UserService.java
src/main/java/com/example/demo/service/user/UserServiceImpl.java

- 닉네임 중복확인 요청 API 및 비즈니스 로직 구현
- 이미 존재하는 닉네임인 경우, UserCustomException으로 예외처리

[feature/25-check-nickname] 닉네임 중복확인 로직 구현

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/dto/board/Response/BoardSearchResponseDto.java
src/main/java/com/example/demo/repository/board/BoardRepositoryCustom.java
src/main/java/com/example/demo/repository/board/BoardRepositoryCustomImpl.java
src/main/java/com/example/demo/service/board/BoardService.java

게시글 검색에 관하여 
BoardController, BoardSearchRequestResponseDto, BoardRepositoryCustom, BoardRepositoryCustomImpl, BoardService 개발

[feature/3-create-board-controller] BoardController 추가

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/dto/board/Response/BoardDetailResponseDto.java
src/main/java/com/example/demo/dto/board/Response/BoardTotalDetailResponseDto.java
src/main/java/com/example/demo/dto/boardposition/BoardPositionDetailResponseDto.java
src/main/java/com/example/demo/dto/position/response/PositionResponseDto.java
src/main/java/com/example/demo/dto/project/response/ProjectDetailResponseDto.java
src/main/java/com/example/demo/dto/user/response/UserBoardDetailResponseDto.java
src/main/java/com/example/demo/dto/user/response/UserProjectResponseDto.java
src/main/java/com/example/demo/global/exception/customexception/BoardCustomException.java
src/main/java/com/example/demo/model/board/Board.java
src/main/java/com/example/demo/service/board/BoardService.java

Feature/3 create board controller 게시글 상세 코드 추가

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/dto/board/Response/BoardCreateResponseDto.java
src/main/java/com/example/demo/global/exception/customexception/ProjectMemberAuthCustomException.java
src/main/java/com/example/demo/global/exception/customexception/TrustGradeCustomException.java
src/main/java/com/example/demo/global/exception/customexception/UserCustomException.java
src/main/java/com/example/demo/service/board/BoardService.java

게시글 생성 컨트롤러
유저 익셉션 수정
게시글 생성 서비스 수정
신용등급 익셉션 생성

[feature/3-create-board-controller] 게시글 생성

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/service/board/BoardService.java

[feature/3-create-board-controller] 게시글 삭제

---

src/main/java/com/example/demo/service/board/BoardService.java

[feature/3-create-board-controller] 게시글 서비스

---

src/main/java/com/example/demo/repository/board/BoardRepositoryCustomImpl.java

BoardRepositoryCustomImpl 에서 pagination과 fetchjoin을 같이 쓰면 안나옴.

[feature/3-create-board-controller] 페이지네이션 OneToMany batchsize 적용

---

src/main/java/com/example/demo/model/project/Project.java
src/main/java/com/example/demo/repository/board/BoardRepositoryCustomImpl.java
src/main/java/com/example/demo/repository/project/ProjectTechnologyRepository.java
src/main/java/com/example/demo/service/board/BoardService.java

Feature/3 create board controller 프로젝트 기술 생성 및 프로젝트 검색 시 기술 나오도록 설정

---

src/main/java/com/example/demo/dto/project/request/ProjectUpdateRequestDto.java
src/main/java/com/example/demo/service/board/BoardService.java

프로젝트 업데이트 시 프로젝트 기술 수정 및
프로젝트 업데이트 DTO 수정

[feature/3-create-board-controller] 프로젝트 업데이트 시 프로젝트 기술 수정

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/dto/board/request/BoardUpdateRequestDto.java
src/main/java/com/example/demo/model/board/Board.java
src/main/java/com/example/demo/model/project/Project.java
src/main/java/com/example/demo/service/board/BoardService.java

게시글 수정 시 BoardPosition 변경되도록 수정
게시글 수정 시 프로젝트 기술 변경되도록 수정
게시글 수정 시 업데이트는 엔티티에서 변경되도록 수정

[feature/3-create-board-controller] 게시글 수정 변경

---

src/main/java/com/example/demo/dto/project/response/ProjectDetailResponseDto.java
src/main/java/com/example/demo/service/board/BoardService.java

[feature/3-create-board-controller] 게시글 상세 프로젝트기술 추가

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/dto/project/response/ProjectSearchResponseDto.java
src/main/java/com/example/demo/repository/board/BoardRepositoryCustomImpl.java

[feature/3-create-board-controller] 게시글 검색 기술 스택 추가

---

src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/dto/project/response/ProjectMeResponseDto.java
src/main/java/com/example/demo/dto/projectmember/response/MyProjectMemberResponseDto.java
src/main/java/com/example/demo/dto/user/response/UserMyProjectResponseDto.java
src/main/java/com/example/demo/repository/project/ProjectRepository.java
src/main/java/com/example/demo/service/project/ProjectService.java

Feature/3 create project controller 내 프로젝트 목록 조회

---

src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/repository/project/ProjectRepository.java
src/main/java/com/example/demo/service/project/ProjectService.java

Feature/3 create project controller 프로젝트 내 목록 조회 일부 수정

---

src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/dto/project/request/ProjectParticipateRequestDto.java
src/main/java/com/example/demo/model/alert/Alert.java
src/main/java/com/example/demo/service/project/ProjectService.java

Feature/3 create project controller 프로젝트 참여 알림 전송 개발

---

src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/dto/project/request/ProjectConfirmRequestDto.java
src/main/java/com/example/demo/repository/project/ProjectMemberAuthRepository.java
src/main/java/com/example/demo/service/project/ProjectService.java

Feature/3 create project controller 프로젝트 참여 개발

---

src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/model/project/Project.java
src/main/java/com/example/demo/service/project/ProjectService.java

[feature/3-create-project-controller] 프로젝트 종료 개발

---

src/main/java/com/example/demo/controller/project/ProjectMemberController.java
src/main/java/com/example/demo/service/project/ProjectMemberService.java

[feature/6-create-project-member]  특정 프로젝트 멤버 탈퇴 수락하기.

---

src/main/java/com/example/demo/controller/project/ProjectMemberController.java
src/main/java/com/example/demo/service/project/ProjectMemberService.java

[feature/6-create-project-member] 프로젝트 멤버 강제 탈퇴 시키기

---

src/main/java/com/example/demo/controller/position/PositionController.java
src/main/java/com/example/demo/service/position/PositionService.java
src/main/java/com/example/demo/service/position/PositionServiceImpl.java

- 포지션(직무) 목록을 조회하는 로직 구현
- 요청 시 DB에 저장된 포지션 목록을 PositionInfoResponseDto로 변환해 List 타입으로 응답

[feature/25-get-position-list] 포지션(직무) 목록 조회 로직 구현

---

src/main/java/com/example/demo/controller/technology_stack/TechnologyStackController.java
src/main/java/com/example/demo/service/technology_stack/TechnologyStackService.java
src/main/java/com/example/demo/service/technology_stack/TechnologyStackServiceImpl.java

- 기술스택 목록을 조회하는 로직 구현
- 요청 시 DB에 저장된 기술스택 목록을 TechnologyStackInfoResponseDto로 변환해 List 타입으로 응답

[feature/25-get-technology-stack-list] 기술스택 목록 조회 로직 구현

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/dto/board/request/BoardCreateRequestDto.java
src/main/java/com/example/demo/dto/project/request/ProjectCreateRequestDto.java
src/main/java/com/example/demo/service/board/BoardPositionService.java
src/main/java/com/example/demo/service/board/BoardPositionServiceImpl.java
src/main/java/com/example/demo/service/board/BoardProjectFacade.java
src/main/java/com/example/demo/service/board/BoardService.java
src/main/java/com/example/demo/service/position/PositionService.java
src/main/java/com/example/demo/service/position/PositionServiceImpl.java
src/main/java/com/example/demo/service/project/ProjectMemberAuthService.java
src/main/java/com/example/demo/service/project/ProjectMemberAuthServiceImpl.java
src/main/java/com/example/demo/service/project/ProjectMemberService.java
src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java
src/main/java/com/example/demo/service/project/ProjectService.java
src/main/java/com/example/demo/service/project/ProjectTechnologyService.java
src/main/java/com/example/demo/service/project/ProjectTechnologyServiceImpl.java
src/main/java/com/example/demo/service/technology_stack/TechnologyStackService.java
src/main/java/com/example/demo/service/technology_stack/TechnologyStackServiceImpl.java
src/main/java/com/example/demo/service/trust_grade/TrustGradeService.java
src/main/java/com/example/demo/service/user/UserProjectHistoryService.java
src/main/java/com/example/demo/service/user/UserProjectHistoryServiceImpl.java
src/main/java/com/example/demo/service/user/UserService.java
src/main/java/com/example/demo/service/user/UserServiceImpl.java

[feature/6-refactoring-board] 보드 게시글 생성 모두 서비스로 하도록 설정

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/service/board/BoardService.java
src/main/java/com/example/demo/service/board/BoardServiceImpl.java

[feature/6-refactoring-board] 게시글 상세

---

src/main/java/com/example/demo/controller/board/BoardController.java

[feature/6-refactoring-board] 게시글 상세 주석 해제

---

src/main/java/com/example/demo/dto/user/response/UserLoginSuccessResponseDto.java

- 회원 로그인 성공 시 필요한 정보 응답을 위해 UserLoginSuccessResponseDto 구현

[feature/74-create-login-response-dto] 회원 로그인 성공 응답 DTO 생성

---

src/main/java/com/example/demo/service/board/BoardProjectFacade.java

Feature/6 refactoring board 게시글 컨트롤러 수정

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/service/board/BoardFacade.java

Feature/6 refactoring project BoardFacade로 이름 변경

---

src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/service/board/BoardFacade.java
src/main/java/com/example/demo/service/project/ProjectFacade.java
src/main/java/com/example/demo/service/project/ProjectMemberAuthService.java
src/main/java/com/example/demo/service/project/ProjectMemberAuthServiceImpl.java
src/main/java/com/example/demo/service/project/ProjectMemberService.java
src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java
src/main/java/com/example/demo/service/project/ProjectServiceImpl.java

[feature/6-refactoring-project] 프로젝트 멤버 컨펌 추가

---

src/main/java/com/example/demo/service/project/ProjectServiceImpl.java

[feature/6-refactoring-project] 프로젝트 종료 수정

---

src/main/java/com/example/demo/service/project/ProjectServiceImpl.java

[feature/6-refactoring-project] 필요없는 줄 삭제

---

src/main/java/com/example/demo/controller/project/ProjectMemberController.java
src/main/java/com/example/demo/service/project/ProjectMemberService.java
src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java

[feature/6-refactoring-project-member] 프로젝트 멈버 강제 탈퇴 개발

---

src/main/java/com/example/demo/security/jwt/JsonWebTokenProvider.java
src/main/resources/application.properties

- properties에서 AccessToken, RefreshToken 만료시간을 셋팅하고 JsonWebTokenProvider에서 해당 값을 가져와 필드에 주입하도록 수정

[feature/74-fix-jwt] JWT 수정

---

src/main/java/com/example/demo/security/jwt/JsonWebTokenProvider.java
src/main/resources/application.properties

[feature/74-fix-jwt] 작업내용 Revert

[revert-93-feature/74-fix-jwt] JWT 수정 Revert

---

src/main/java/com/example/demo/global/config/RedisConfig.java
src/main/resources/application.properties

- AWS Elasti Cache 설정 셋팅
- RedisTemplate value 타입 Object -> String 변경

[feature/74-fix-redis-config] Redis 설정 수정

---

src/main/java/com/example/demo/service/board/BoardPositionServiceImpl.java

[feature/6-refactoring-project-member] Service 추가

---

src/main/java/com/example/demo/service/board/BoardPositionServiceImpl.java

[feature/6-create-refactoring-project-member] BoardPosition builder 추가

---

src/main/resources/application.properties

- 연산식으로 되어 있던 토큰 만료시간 계산된 값으로 수정
- 환경변수 대문자로 수정

[feature/74-refactor-jwt] JWT 관련 설정 셋팅 수정

---

src/main/java/com/example/demo/controller/project/ProjectMemberController.java
src/main/java/com/example/demo/dto/project/response/ProjectMemberReadCrewDetailResponseDto.java
src/main/java/com/example/demo/repository/project/ProjectRepository.java
src/main/java/com/example/demo/service/project/ProjectMemberAuthServiceImpl.java
src/main/java/com/example/demo/service/project/ProjectMemberFacade.java
src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java
src/main/java/com/example/demo/service/project/ProjectService.java
src/main/java/com/example/demo/service/project/ProjectServiceImpl.java
src/main/java/com/example/demo/service/user/UserCrewDetailResponseDto.java

[feature/6-create-refactoring-project-member] 크루정보 상세 개발

---

src/main/java/com/example/demo/controller/project/ProjectMemberController.java
src/main/java/com/example/demo/dto/projectmember/response/ProjectMemberReadCrewDetailResponseDto.java
src/main/java/com/example/demo/dto/projectmember/response/ProjectMemberReadProjectCrewsResponseDto.java
src/main/java/com/example/demo/dto/user/response/UserCrewDetailResponseDto.java
src/main/java/com/example/demo/dto/user/response/UserReadProjectCrewResponseDto.java
src/main/java/com/example/demo/service/project/ProjectMemberFacade.java
src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java

크루정보 상세 페이지 인트로, 사용자 스택, TODO 작성

Feature/6 create refactoring project member 크루정보 상세 페이지 개발

---

src/main/java/com/example/demo/dto/trust_score/ProjectUserHistoryDto.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreHistoryRepositoryImpl.java

상세 크루 페이지 화면에 보여질 프로젝트 참여자의 신뢰점수 내역에 대한 DTO와 쿼리입니다

[feature/76-project-user-history] feat : 프로젝트 크루 상세 정보 신뢰점수이력 DTO, 쿼리 개발

---

src/main/java/com/example/demo/dto/user/request/UserCreateRequestDto.java

- UserCreateRequestDto password 필드의 레직스 수정, 기존의 레직스가 테스트 시 동작하지 않는 버그 수정

[feature/74-fix-user-create-dto] 회원 등록 DTO 수정

---

src/main/java/com/example/demo/service/user/UserFacade.java

- 다양한 도메인의 Service 의존성 주입을 관리하기 위해 UserFacade 상위 서비스 생성

[feature/74-create-user-facade-service] UserFacade 서비스 생성

---

src/main/java/com/example/demo/dto/user/response/UserReadProjectCrewResponseDto.java

[feature/6-create-refacotring-project-member] 크루정보 유저 profileImgSrc 추가

---

src/main/java/com/example/demo/constant/TrustScoreTypeIdentifier.java

회원점수타입에 대한 상수 클래스 생성하였습니다
TrustScoreRequestDto 생성하시고 필드에 값 넣어주실 때
실수를 줄이기 위해 여기에 있는 값들을 static variable 형태로 대입해주시면 편할 것 같아서 만들었습니다.

[feature/76-score-type-id-class] feat : 신뢰점수타입 설정 클래스 생성

---

src/main/java/com/example/demo/repository/work/WorkRepository.java
src/main/java/com/example/demo/service/project/ProjectMemberFacade.java
src/main/java/com/example/demo/service/work/WorkService.java
src/main/java/com/example/demo/service/work/WorkServiceImpl.java

[feature/6-create-refactoring-project-member] fix : 프로젝트 내 크루정보들 조회

---

src/main/java/com/example/demo/controller/milestone/MileStoneController.java
src/main/java/com/example/demo/dto/milestone/request/MilestoneCreateRequestDto.java
src/main/java/com/example/demo/dto/milestone/response/MilestoneCreateResponseDto.java
src/main/java/com/example/demo/service/milestone/MileStoneFacade.java
src/main/java/com/example/demo/service/milestone/MilestoneService.java

[feature/6-create-refactoring-milestone] 마일스톤 생성 개발

---

src/main/java/com/example/demo/controller/milestone/MileStoneController.java

[feature/6-create-refactoring-millestone] 마일스톤 필요 없는 import 제거

---

src/main/java/com/example/demo/controller/milestone/MileStoneController.java
src/main/java/com/example/demo/global/exception/customexception/MilestoneCustomException.java
src/main/java/com/example/demo/repository/milestone/MileStoneRepository.java
src/main/java/com/example/demo/service/milestone/MileStoneFacade.java
src/main/java/com/example/demo/service/milestone/MilestoneService.java
src/main/java/com/example/demo/service/milestone/MilestoneServiceImpl.java

[feature/6-create-refactoring-milestone] feat : 프로젝트의 모든 마일스톤 조회

---

src/main/java/com/example/demo/controller/milestone/MileStoneController.java
src/main/java/com/example/demo/service/milestone/MilestoneService.java
src/main/java/com/example/demo/service/milestone/MilestoneServiceImpl.java

[feature/6-create-refactoring-milestone] 마일스톤 하나 조회

---

src/main/java/com/example/demo/controller/milestone/MileStoneController.java
src/main/java/com/example/demo/dto/milestone/request/MileStoneUpdateRequestDto.java
src/main/java/com/example/demo/model/milestone/Milestone.java
src/main/java/com/example/demo/service/milestone/MilestoneService.java
src/main/java/com/example/demo/service/milestone/MilestoneServiceImpl.java

[feature/6-create-refactoring-milestone] 마일스톤 업데이트 개발

---

src/main/java/com/example/demo/controller/milestone/MileStoneController.java
src/main/java/com/example/demo/dto/milestone/request/MilestoneUpdateContentRequestDto.java
src/main/java/com/example/demo/dto/milestone/request/MilestoneUpdateDateRequestDto.java
src/main/java/com/example/demo/model/milestone/Milestone.java
src/main/java/com/example/demo/service/milestone/MilestoneService.java
src/main/java/com/example/demo/service/milestone/MilestoneServiceImpl.java

[feature/6-create-refactoring-milestone] 마일스톤 삭제

---

src/main/java/com/example/demo/controller/work/WorkController.java
src/main/java/com/example/demo/dto/milestone/response/MilestoneReadResponseDto.java
src/main/java/com/example/demo/dto/work/request/WorkCreateRequestDto.java
src/main/java/com/example/demo/global/exception/customexception/MilestoneCustomException.java
src/main/java/com/example/demo/repository/milestone/MileStoneRepository.java
src/main/java/com/example/demo/service/milestone/MilestoneService.java
src/main/java/com/example/demo/service/milestone/MilestoneServiceImpl.java
src/main/java/com/example/demo/service/project/ProjectMemberService.java
src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java
src/main/java/com/example/demo/service/work/WorkFacade.java
src/main/java/com/example/demo/service/work/WorkService.java
src/main/java/com/example/demo/service/work/WorkServiceImpl.java

Feature/6 create refactoring work 업무 개발

---

src/main/java/com/example/demo/controller/work/WorkController.java
src/main/java/com/example/demo/dto/work/request/WorkReadResponseDto.java
src/main/java/com/example/demo/service/work/WorkFacade.java
src/main/java/com/example/demo/service/work/WorkService.java
src/main/java/com/example/demo/service/work/WorkServiceImpl.java

[feature/6-create-refactoring-work] 마일스톤의 작업들 조회 개발

---

src/main/java/com/example/demo/controller/work/WorkController.java
src/main/java/com/example/demo/service/work/WorkService.java
src/main/java/com/example/demo/service/work/WorkServiceImpl.java

[feature/6-create-refactoring-work] 작업 하나 조회

---

src/main/java/com/example/demo/controller/work/WorkController.java
src/main/java/com/example/demo/dto/work/request/WorkUpdateRequestDto.java
src/main/java/com/example/demo/model/work/Work.java
src/main/java/com/example/demo/service/work/WorkFacade.java

[feature/6-create-refactoring-work] 작업 수정 개발

---

src/main/java/com/example/demo/controller/work/WorkController.java
src/main/java/com/example/demo/service/work/WorkService.java
src/main/java/com/example/demo/service/work/WorkServiceImpl.java

[feature/6-create-refactoring-work] 작업 하나 삭제 개발

---

src/main/java/com/example/demo/controller/work/WorkController.java
src/main/java/com/example/demo/dto/work/request/WorkUpdateContentRequestDto.java
src/main/java/com/example/demo/model/work/Work.java
src/main/java/com/example/demo/service/work/WorkFacade.java
src/main/java/com/example/demo/service/work/WorkServiceImpl.java

[feature/6-create-refactoring-work] 업무 내용 변경

---

src/main/java/com/example/demo/controller/work/WorkController.java
src/main/java/com/example/demo/dto/work/request/WorkUpdateCompleteStatusRequestDto.java
src/main/java/com/example/demo/model/work/Work.java
src/main/java/com/example/demo/service/work/WorkFacade.java

[feature/6-create-refactoring-work] 업무 작업상태 변경 개발

---

src/main/java/com/example/demo/model/work/Work.java

[feature/6-create-refactoring-work] 업무완료날짜 추가

---

src/main/java/com/example/demo/controller/milestone/MileStoneController.java
src/main/java/com/example/demo/service/milestone/MilestoneService.java
src/main/java/com/example/demo/service/milestone/MilestoneServiceImpl.java

[feature/6-create-refactoring-work] 마일스톤 implements 추가

---

src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/service/project/ProjectFacade.java
src/main/java/com/example/demo/service/project/ProjectMemberFacade.java
src/main/java/com/example/demo/service/project/ProjectService.java

[feature/6-create-refactoring-work] ProjectController RequiredArgsConstructor 추가, final로 변경

---

src/main/java/com/example/demo/service/board/BoardFacade.java
src/main/java/com/example/demo/service/board/BoardPositionService.java
src/main/java/com/example/demo/service/board/BoardService.java
src/main/java/com/example/demo/service/board/BoardServiceImpl.java
src/main/java/com/example/demo/service/milestone/MilestoneService.java
src/main/java/com/example/demo/service/project/ProjectFacade.java
src/main/java/com/example/demo/service/project/ProjectMemberAuthService.java
src/main/java/com/example/demo/service/project/ProjectMemberService.java
src/main/java/com/example/demo/service/project/ProjectService.java
src/main/java/com/example/demo/service/project/ProjectTechnologyService.java
src/main/java/com/example/demo/service/user/UserProjectHistoryService.java
src/main/java/com/example/demo/service/work/WorkFacade.java
src/main/java/com/example/demo/service/work/WorkService.java

Transactional, @Service Impl에 추가

[feature/6-create-refactoring-work] Transactional, @Service Impl에 추가

---

src/main/java/com/example/demo/global/config/SecurityConfig.java
src/main/java/com/example/demo/security/custom/UserAuthenticationFilter.java

- JsonWebTokenAuthenticationFilter -> UserAuthenticationFilter로 이름 변경

[feature/74-security-filter-rename] JsonWebTokenAuthenticationFilter 이름 변경

---

src/main/java/com/example/demo/global/config/SecurityConfig.java

- 기존 필터명 변경에 따라 필터를 관리하는 클래스 JsonWebTokenAuthenticationFilterConfigurer -> UserAuthenticationFilterConfigurer로 변경
- AuthenticationManager 빈 등록 방법 변경
- UserAuthenticationFilterConfigurer에서 AuthenticationManger 인스턴스를 가져오는 로직 수정

[feature/74-fix-security-config] SecurityConfig 수정

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreController.java
src/main/java/com/example/demo/dto/trust_score/AddPointDto.java
src/main/java/com/example/demo/dto/trust_score/request/TrustScoreUpdateRequestDto.java
src/main/java/com/example/demo/global/validation/annotation/ValidTrustScoreUpdateRequest.java
src/main/java/com/example/demo/global/validation/validator/TrustScoreUpdateRequestValidator.java
src/main/java/com/example/demo/service/trust_score/TrustScoreService.java
src/main/java/com/example/demo/service/trust_score/TrustScoreServiceImpl.java

TrustScoreUpdateRequestoDto의 
1. Validator 적용
2. 부담 줄이는 서비스 전용 DTO 개발 및 적용

[Feature/76-refactor-trustscore-controller-and-service] refactor : 컨트롤러 서비스 리팩토링

---

src/main/java/com/example/demo/repository/trust_score/TrustScoreRepository.java

사용자 ID로 신뢰점수 반환하는 Spring Data JPA 메서드 추가

[feature/76-trustscore-search-method] feat : 사용자 ID로 신뢰점수 반환

---

src/main/java/com/example/demo/global/validation/annotation/ValidAddPointDto.java
src/main/java/com/example/demo/global/validation/validator/AddPointDtoValidator.java
src/main/java/com/example/demo/global/validation/validator/TrustScoreUpdateRequestValidator.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryCustom.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryImpl.java

유효성 검증을 위한 추가 로직을 개발했습니다
1. AddPointDto validation 로직 추가 개발
2. 상위분류 신뢰저무타입 조회 개발

[feature/76-add-validate-logic] feat : 유효성 검증을 위한 추가 로직 개발

---

src/main/java/com/example/demo/model/board/Board.java
src/main/java/com/example/demo/service/board/BoardServiceImpl.java

getDetail 가져올 시에 pageView도 상승시킴.

Feature/6 create project member 

---

src/main/java/com/example/demo/controller/alert/AlertController.java
src/main/java/com/example/demo/dto/alert/AlertCreateRequestDto.java
src/main/java/com/example/demo/model/alert/Alert.java
src/main/java/com/example/demo/service/alert/AlertFacade.java
src/main/java/com/example/demo/service/alert/AlertService.java
src/main/java/com/example/demo/service/alert/AlertServiceImpl.java

[feature/75-create-refactoring-alert] 알림 생성 개발

---

src/main/java/com/example/demo/constant/AlertType.java
src/main/java/com/example/demo/controller/alert/AlertController.java
src/main/java/com/example/demo/dto/alert/AlertCreateRequestDto.java
src/main/java/com/example/demo/repository/alert/AlertRepository.java
src/main/java/com/example/demo/repository/board/BoardRepositoryCustomImpl.java
src/main/java/com/example/demo/service/alert/AlertFacade.java
src/main/java/com/example/demo/service/alert/AlertService.java
src/main/java/com/example/demo/service/alert/AlertServiceImpl.java

Feature/75 create refactoring alert 프로젝트 알림 개발

---

src/main/java/com/example/demo/model/trust_score/TrustScoreType.java
src/main/resources/data.sql
src/main/resources/schema.sql

[feature/76-add-data-schema] feat : 신뢰점수타입관련 테이블 및 테이터 생성

---

src/main/java/com/example/demo/constant/TrustScoreTypeIdentifier.java
src/main/java/com/example/demo/global/validation/validator/AddPointDtoValidator.java
src/main/java/com/example/demo/global/validation/validator/TrustScoreUpdateRequestValidator.java
src/test/java/com/example/demo/service/trust_score/AddPointTest.java

AddPointDto, 신뢰점수 API Request Dto 유효성 검증 (미완성)
유효성 검증의 일부를 완료했습니다.

[feature/76-unit-test] test : AddPointDto, 신뢰점수 API Request Dto 유효성 검증

---

src/main/java/com/example/demo/constant/TrustScoreTypeIdentifier.java
src/main/java/com/example/demo/global/validation/validator/AddPointDtoValidator.java
src/main/java/com/example/demo/global/validation/validator/TrustScoreUpdateRequestValidator.java

유효성 검증 실패시, boolean을 return할 수 있게 fix

[feature/76-refactor-validation-logic] fix : 유효성 검증 boolean 변경

---

src/main/java/com/example/demo/global/config/SecurityConfig.java
src/main/java/com/example/demo/security/custom/AuthenticationExceptionFilter.java

- 시큐리티 인증과정 중 발생하는 예외를 처리하는 커스텀 필터 구현, 시큐리티 필터체인에 등록
- 사용자 인증 과정 중 발생하는 예외와 JsonWebToken을 인증하고 검증하는 과정 중 발생하는 예외를 AuthenticationExceptionFilter에서 관리하고 예외 응답을 하도록 구현
#74

[feature/74-security-authentication-exception] 시큐리티 인증과정 예외 필터 구현

---

src/main/java/com/example/demo/global/config/SecurityConfig.java
src/main/java/com/example/demo/security/jwt/JsonWebTokenAuthenticationFilter.java
src/main/java/com/example/demo/security/jwt/JsonWebTokenExceptionFilter.java

- 기존 JsonWebTokenAuthorizationFilter -> JsonWebTokenAuthenticationFilter로 변경, JWT 검증 및 인증을 수행하기 때문에 담당 역할에 맞도록 네이밍 수정
- 기존 AuthenticationExceptionFilter -> JsonWebTokenExceptionFilter로 변경, 회원 인증과 JWT 인증을 따로 구분해서 처리되도록 수정하여 AuthenticationExceptionFilter에서는 JWT 예외만 처리하기 때문에 네이밍 수정
#163

[feature/163-fix-security-jwt] JWT 관련 시큐리티 필터 수정

---

src/main/java/com/example/demo/controller/work/WorkController.java
src/main/java/com/example/demo/dto/project/response/ProjectSpecificDetailResponseDto.java
src/main/java/com/example/demo/service/project/ProjectFacade.java
src/main/java/com/example/demo/service/work/WorkFacade.java

프로젝트 상세 works, milestones, users 다 뻄.

[feature/75-change-work] change : 프로젝트 내 업무 조회 추가

---

src/main/java/com/example/demo/controller/milestone/MileStoneController.java
src/main/java/com/example/demo/service/milestone/MileStoneFacade.java

[feature/75-fix-milestone] 마일스톤 URL 변경

---

src/main/java/com/example/demo/global/config/CorsConfig.java
src/main/java/com/example/demo/global/config/SecurityConfig.java

- CorsConfig 파일에 cors 초기 설정
- SecurityConfig 파일에 CorsConfig 등록
#163

[feature/163-security-cors-config] 시큐리티 cors 초기 설정

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreController.java
src/main/java/com/example/demo/dto/trust_score/AddPointDto.java
src/main/java/com/example/demo/dto/trust_score/request/TrustScoreUpdateRequestDto.java
src/main/java/com/example/demo/service/trust_score/TrustScoreService.java
src/main/java/com/example/demo/service/trust_score/TrustScoreServiceImpl.java

[feature/76-validation] fix : AddPointDto 유효성 검사 작동 안 하는 버그 수정

---

src/main/java/com/example/demo/controller/user/UserController.java

- UserController에 테스트했던 api 삭제

[feature/fix-user-controller] UserController test api 삭제

---

src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryImpl.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreTypeRepositoryTest.java

TrustScoreTypeRepository의
getScore()
getScoreByProject()
findAllUpScoreTypeId()
메서드들을 테스트했습니다

[feature/175-repo-test] test : TrustScoreTypeRepository 메서드 테스트

---

src/main/java/com/example/demo/controller/milestone/MileStoneController.java
src/main/java/com/example/demo/dto/milestone/request/MilestoneCreateRequestDto.java

Feature/75 fix milestone 마일스톤 테스트 검증 

---

src/main/java/com/example/demo/dto/milestone/request/MilestoneUpdateContentRequestDto.java

NotBlank, NoArgsConstructor 추가

[feature/75-fix-milesone] NotBlank, NoArgsConstructor 추가

---

src/main/java/com/example/demo/controller/work/WorkController.java
src/main/java/com/example/demo/dto/work/request/WorkUpdateAssignUserRequestDto.java
src/main/java/com/example/demo/dto/work/request/WorkUpdateCompleteStatusRequestDto.java
src/main/java/com/example/demo/service/work/WorkFacade.java

RequestBody 추가
NoArgsConstructor 추가

[feature/75-create-refactoring-work] RequestBody 추가

---

src/main/java/com/example/demo/repository/alert/AlertRepository.java

Feature/75 create refactoring alert enum타입 수정

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreController.java
src/main/java/com/example/demo/dto/trust_grade/response/TrustGradeResponseDto.java
src/main/java/com/example/demo/model/trust_grade/TrustGrade.java
src/main/java/com/example/demo/model/trust_score/TrustScore.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreRepositoryCustom.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreRepositoryImpl.java
src/main/java/com/example/demo/service/trust_score/TrustScoreServiceImpl.java
src/main/resources/data.sql
src/main/resources/schema.sql

신뢰등급 엔티티 관련 
data.sql, schema.sql 변경
신뢰등급 업데이트 스케줄러 및 개별유저 업데이트 기능 추가

[feature/175-update-grade] feat : 개별 유저 / 배치 신뢰등급 업데이트 기능 추가

---

src/main/java/com/example/demo/model/trust_score/TrustScore.java
src/main/java/com/example/demo/model/trust_score/TrustScoreHistory.java
src/main/java/com/example/demo/service/trust_score/TrustScoreServiceImpl.java

신뢰점수 도메인 내 모델들의 생성일, 변경일을 추가했습니다

[feature/175-fix-entity] fix : 생성일, 변경일 추가

---

src/main/java/com/example/demo/global/exception/customexception/TrustScoreCustomException.java
src/main/java/com/example/demo/global/exception/errorcode/TrustScoreErrorCode.java

TrustScore 관련 Custom 예외를 생성하였습니다.
trustScoreRepository.findByUserId(Long userId);
호출시 사용 용도로 만들었습니다.

[feature/175-add-exception] feat : TrustScoreCustomException 생성

---

src/main/java/com/example/demo/dto/trust_score/ProjectUserHistoryDto.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreHistoryRepositoryImpl.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreHistoryRepositoryTest.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreRepositoryTest.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreTypeRepositoryTest.java

TrustScoreRepository
TrustScoreTypeRepository
TrustScoreHistoryRepository
단위테스트 입니다.

[feature/175-trustscore-repo-test] test : 신뢰점수 repository 단위테스트

---

src/main/java/com/example/demo/dto/user/response/UserLoginSuccessResponseDto.java
src/main/java/com/example/demo/security/custom/UserAuthenticationSuccessHandler.java

- 회원 로그인 성공 응답 DTO에서 nickname, profileImgSrc 필드 삭제
- PrincipalDetails 클래스를 수정하면서 로그인 로직 중 로그인 성공 응답을 셋팅하는 과정 중에서 발생한 버그 수정

[feature/fix-user-login] 로그인 버그 수정

---

src/main/java/com/example/demo/service/trust_score/TrustScoreService.java
src/main/java/com/example/demo/service/trust_score/TrustScoreServiceImpl.java
src/main/java/com/example/demo/service/user/UserFacade.java

TrustScoreServiceImpl class의 getScore 메서드를 리팩토링 했습니다.

[feature/175-refactor-method] TrustScoreServiceImpl getScore 메서드 리팩토링

---

src/test/java/com/example/demo/temporary/UserFacadeTest.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreHistoryRepositoryTest.java
src/test/java/com/example/demo/trust_score/service/TrustScoreServiceTest.java

UserFacade
TrustScoreService
의 단위테스트를 생성 및 수행하였고,
TrustScoreHistoryRepository
의 단위테스트를 수정하였습니다.

[feature/175-unit-tests] test : 신뢰점수 서비스 단위테스트 및 수정

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreTypeController.java
src/main/java/com/example/demo/dto/trust_score_type/response/TrustScoreTypeReadResponseDto.java
src/main/java/com/example/demo/global/exception/customexception/TrustScoreTypeCustomException.java
src/main/java/com/example/demo/global/exception/errorcode/TrustScoreTypeErrorCode.java
src/main/java/com/example/demo/model/trust_score/TrustScoreType.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryCustom.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryImpl.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeService.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeServiceImpl.java
src/main/resources/schema.sql
src/test/java/com/example/demo/trust_score/controller/TrustScoreTypeControllerTest.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreTypeRepositoryTest.java
src/test/java/com/example/demo/trust_score/service/TrustScoreTypeServiceTest.java

1. 신뢰점수타입 엔티티 및 스키마 변경
2. 전체 조회 관련 Controller, Service, Repository 구현
3. 각 layer에 대한 테스트 구현 및 통과

[feat/175-get-types] feat : 전체 신뢰점수타입 조회 기능 추가

---

src/main/java/com/example/demo/service/user/UserFacade.java

- 회원 엔티티와 회원 기술스택 엔티티의 연쇄 옵션을 삭제함으로써 회원 기술스택 엔티티를 별도로 저장하는 로직을 추가하여 회원가입 로직 수정
- 회원가입 로직 코드 중 공통으로 사용할 코드를 분리하고 리팩토링

[feature/163-fix-user-signup] 회원가입 로직 수정 및 코드 리팩토링

---

src/main/java/com/example/demo/repository/user/UserRepository.java
src/main/java/com/example/demo/repository/user/UserRepositoryCustom.java
src/main/java/com/example/demo/repository/user/UserRepositoryImpl.java

- User 영역에서 queryDsl을 사용하기 위해 UserRepositoryCustom, UserRepositoryImpl 클래스 생성

[feature/163-create-querydsl-user-repository] 회원 커스텀 레파지토리 생성

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreTypeController.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryImpl.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreTypeRepositoryTest.java

Projections.constructor() 사용 시 left join 안 되는 이슈를 해결하여
코드를 더 간결하게 바꿈

[feat/175-refactor-repo] fix : left join 안 되는 issue 해결

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreController.java
src/main/java/com/example/demo/controller/trust_score/TrustScoreTypeController.java
src/main/java/com/example/demo/dto/trust_score_type/request/TrustScoreTypeCreateRequestDto.java
src/main/java/com/example/demo/dto/trust_score_type/response/TrustScoreTypeCreateResponseDto.java
src/main/java/com/example/demo/model/trust_score/TrustScoreType.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeService.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeServiceImpl.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreTypeRepositoryTest.java
src/test/java/com/example/demo/trust_score/service/TrustScoreTypeServiceTest.java

신뢰점수타입 요청, 응답 DTO 클래스 구현
신뢰점수타입을 생성하기 위한 Controller, Service, Repository 레이어 구현
신뢰점수타입 확인하는 테스트 구현 및 통과 확인

[feature/175-create-types] feat : 신뢰점수타입 생성 기능 개발

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreTypeController.java
src/main/java/com/example/demo/dto/trust_score/ProjectUserHistoryDto.java
src/main/java/com/example/demo/model/trust_score/TrustScoreType.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeService.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeServiceImpl.java
src/test/java/com/example/demo/trust_score/service/TrustScoreTypeServiceTest.java

개별 신뢰점수타입의 정보를 조회하는 기능을 생성하였습니다.
Controller, Service layer를 구현하였고, 테스트를 완료했습니다.

[feature-175-score-type-info] feat : 신뢰점수타입 정보 조회 기능 구현

---

src/main/java/com/example/demo/dto/user/response/UserLoginSuccessResponseDto.java
src/main/java/com/example/demo/security/custom/PrincipalDetails.java
src/main/java/com/example/demo/security/custom/UserAuthenticationSuccessHandler.java

- 로그인 성공 시 클라이언트로 응답하는 데이터에 nickname 필드 추가
- 커스텀 사용자 인증 정보 PrincipalDetails, 로그인 성공 응답 DTO UserLoginSuccessResponseDto에 nickname 정보 추가

[feature/login-response-refactor] 로그인 응답 수정

---

src/main/java/com/example/demo/service/board/BoardFacade.java
src/main/java/com/example/demo/service/trust_grade/TrustGradeService.java
src/main/java/com/example/demo/service/trust_grade/TrustGradeServiceImpl.java

- 신뢰등급 서비스 계층을 TrustGradeService, TrustGradeServiceImpl로 분리

[feature/refactor-trust-grade-service] 신뢰등급 서비스 계층 분리

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreTypeController.java
src/main/java/com/example/demo/dto/trust_score_type/TrustScoreTypeSearchCriteria.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreRepositoryImpl.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryImpl.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreTypeRepositoryTest.java
src/test/java/com/example/demo/trust_score/service/TrustScoreTypeServiceTest.java

신뢰점수타입에 키워드를 검색하는 기능을 추가하였습니다. 
테스트에 대하여 통과하였습니다.

[feat/175-keyword-search] feat : 신뢰점수타입 키워드 검색 기능 추가

---

src/main/java/com/example/demo/global/util/DateTimeConverter.java

- 날짜 관련 데이터 타입 변환을 담당하는 DateTimeConverter 클래스 생성
- LocalDateTime 타입의 데이터를 String 타입으로 변환하고, String 타입의 날짜 데이터를 LocalDateTime으로 변환하는 로직 구현

[feature/create-date-time-converter] 날짜데이터 타입 변환 클래스 생성

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreTypeController.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryCustom.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryImpl.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeService.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeServiceImpl.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreTypeRepositoryTest.java
src/test/java/com/example/demo/trust_score/service/TrustScoreServiceTest.java

신뢰점수타입 관련 논리적 삭제 (비활성화) 로직을 구현 및 테스트하였습니다.

[feat/175-type-disable] feat : 신뢰점수타입 비활성화 구현

---

src/main/java/com/example/demo/global/exception/customexception/CommonCustomException.java
src/main/java/com/example/demo/global/exception/errorcode/CommonErrorCode.java

- CommonErrorCode에서 클라이언트로부터 잘못된 형식의 입력 데이터가 요청된 경우의 INVALID_VALUE enum 변수명을 INVALID_INPUT_VALUE로 수정
- CommonCustomException에 INVALID_INPUT_VALUE 타입의 예외 추가

[feature/refactor-common-custom-exception] 공통 예외 수정

---

src/main/java/com/example/demo/constant/UserStatus.java
src/main/java/com/example/demo/model/user/User.java

- 회원 상태를 관리하는 UserStatus enum 클래스 추가
- 회원 상태는 ACTIVE(활동), SUSPENDED(정지), DELETED(탈퇴) 3가지로 구분해서 관리
- 회원 엔티티에 UserStatus 타입의 status 필드 추가

[feature/add-user-status-enum] 회원 상태 enum 추가

---

src/main/java/com/example/demo/service/user/UserFacade.java

- 회원가입 로직에서 회원 엔티티 생성 시 status 필드를 UserStatus.ACTIVE 값으로 셋팅하는 코드 추가

[feature/fix-user-signup] 회원가입 로직 수정

---

src/main/java/com/example/demo/controller/user/UserController.java
src/main/java/com/example/demo/service/user/UserFacade.java

- 로그인한 회원의 프로젝트 이력 목록을 페이징으로 조회하는 로직 구현
- 페이징은 offest 방법을 활용해 클라이언트로부터 pageNumber 값을 요청받아 해당 페이지에 있는 프로젝트 이력 목록 데이터를 List<UserProjectHistoryInfoResponseDto> 타입으로 응답
#220

[feature/220-get-my-project-history-list] 내 프로젝트 이력 목록 조회 로직 구현

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreTypeController.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryCustom.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryImpl.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeService.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeServiceImpl.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreTypeRepositoryTest.java

신뢰점수타입 관리자 페이지 관련 
동적 Pagination 과 Sorting 기능을 구현하였습니다.

[feat/175-paging-sorting] feat : 신뢰점수타입 paging/sorting 기능 구현

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/service/board/BoardFacade.java

- 게시글 생성 로직에서 로그인한 회원의 인증 정보를 가져오기 위해 AuthenticationPricipal 어노테이션 등록
- 컨트롤러, 서비스 메소드에 회원 정보 파라미터 추가

[feature/fix-create-board] 게시글 생성 로직 수정

---

src/main/java/com/example/demo/dto/user/response/UserMyInfoResponseDto.java
src/main/java/com/example/demo/service/user/UserFacade.java

- 내 정보 조회 시 응답하는 UserMyInfoResponseDto에 자기소개 intro 필드 추가

[feature/fix-get-myinfo] 내 정보 조회 로직 수정

---

src/main/java/com/example/demo/dto/trust_score_type/TrustScoreTypeBaseDto.java
src/main/java/com/example/demo/dto/trust_score_type/request/TrustScoreTypeCreateRequestDto.java
src/main/java/com/example/demo/dto/trust_score_type/request/TrustScoreTypeUpdateRequestDto.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreHistoryRepositoryTest.java
src/test/java/com/example/demo/trust_score/service/TrustScoreTypeServiceTest.java

신뢰점수타입 기본 DTO를 생성하여,
중복되는 연관 DTO들의 변수에 대해서 기본 DTO를 상속하게 하였습니다.

[feat/175-refactor-dto] refactor : 신뢰점수타입 기본 DTO 생성 및 연관 DTO 상속 설정

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreTypeController.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreTypeRepositoryImpl.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeService.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeServiceImpl.java

Controller-Service 연결되지 않았던 부분을 해소했습니다.

[feat/175-fix-method] fix : Controller-Service 미참조 해결

---

src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/service/project/ProjectFacade.java

- 내 프로젝트 목록 조회 로직에서 로그인한 회원의 인증 정보를 가져오기 위해 AuthenticationPricipal 어노테이션 등록
- ProjectFacade 내 프로젝트 목록 조회 메소드에 회원 ID(PK) 파라미터 추가

[feature/fix-get-my-project] 내 프로젝트 목록 조회 로직 수정

---

src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/service/project/ProjectFacade.java

- 프로젝트 참여하기 알림 보내기 로직에서 로그인한 회원의 인증 정보를 가져오기 위해 AuthenticationPricipal 어노테이션 등록
- ProjectFacade 프로젝트 참여하기 알림 보내기 메소드에 회원 ID(PK) 파라미터 추가

[feature/fix-project-participate] 프로젝트 참여하기 알림 보내기 로직 수정

---

src/main/java/com/example/demo/global/exception/customexception/TrustScoreTypeCustomException.java
src/main/java/com/example/demo/global/exception/errorcode/TrustScoreTypeErrorCode.java
src/main/java/com/example/demo/service/trust_score/TrustScoreTypeServiceImpl.java
src/test/java/com/example/demo/trust_score/service/TrustScoreTypeServiceTest.java

1. 해당 식별자의 신뢰점수타입 존재 여부 확인
2. 해당 식별자의 신뢰점수타입 비활성화 여부 
3. 테스트를 통한 오류 발생 확인

[feat/175-validate-type] feat : 타입 비활성화 유효성 검사 추가

---

src/main/java/com/example/demo/controller/user/UserController.java
src/main/java/com/example/demo/dto/user/response/UserSimpleInfoResponseDto.java
src/main/java/com/example/demo/service/user/UserFacade.java

- 내 정보 중 닉네임, 프로필 이미지 경로 정보만 조회하는 로직 구현
#240

[feature/240-get-simple-myinfo] 간단한 내 정보 조회 로직 구현

---

src/main/java/com/example/demo/controller/trust_score/TrustScoreController.java
src/main/java/com/example/demo/controller/trust_score/TrustScoreTypeController.java
src/main/java/com/example/demo/model/trust_score/TrustScoreType.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreRepositoryCustom.java
src/main/java/com/example/demo/repository/trust_score/TrustScoreRepositoryImpl.java
src/test/java/com/example/demo/trust_score/repository/TrustScoreRepositoryTest.java

TrustScoreRepositoryImpl 중복 메서드 리팩토링하였습니다.

[refactor/175-redun-methods] refactor : 메서드 중복 코드 리팩토링

---

src/main/java/com/example/demo/global/config/SecurityConfig.java

- **/api/admin** 패턴을 가진 URI 요청 시, 요청한 사용자의 권한을 확인해 인가를 허용하도록 설정
- 로그인이 필요없는 요청(인증 과정이 필요없는 요청)에 **/public** 공통 패턴을 추가하여 **/api/public** 패턴을 가진 요청들은 인증과정 없이 모두 접근이 가능하고 그 외 요청들은 인증된 사용자에게만 접근이 허용되도록 설정
#240

[feature/240-security-authorization-config] 시큐리티 인가 설정 추가

---

src/main/java/com/example/demo/controller/user/UserController.java

- UserController에서 중복되는 매핑 URI 패턴을 RequestMapping 어노테이션을 사용해 공통으로 매핑되도록 수정

[feature/refactor-user-controller] UserController 매핑 URI 코드 리팩토링

---

src/main/java/com/example/demo/controller/board/BoardController.java

- BoardController의 게시글 검색 요청 api 로직 수정
- 게시글 검색 요청 시 page 정보를 RequestParam 쿼리 파라미터로 받도록 수정
#240

[feature/240-fix-board-search] 게시글 검색 로직 수정

---

src/main/java/com/example/demo/global/exception/customexception/PageNationCustomException.java
src/main/java/com/example/demo/global/exception/errorcode/PageNationErrorCode.java

- 페이징 관련 예외를 처리하기 위한 PageNationErrorCode 및 PageNationCustomException 생성
- 페이지 번호 예외 추가

[feature/create-page-custom-exception] 페이지 관련 커스텀 예외 생성

---

src/main/java/com/example/demo/global/exception/errorcode/PageNationErrorCode.java

- PageNationErrorCode에서 status, message 값을 가져올 때 null 값을 반환하는 문제가 발생하여  this.status(), this.message() 값을 반환하도록 수정해 문제 해결

[feature/fix-page-errorcode] 페이지 에러코드 수정

---

src/main/java/com/example/demo/constant/ProgressStatus.java

- 요구사항 변경으로 기존 마일스톤, 업무 엔티티의 expired_date, complete_date 필드를 하나의 필드로 관리하기 위해 마일스톤, 업무의 진행 상태를 관리하기 위한 ProgressStatus 생성
- code 값을 통해 요청 값을 매핑하고 응답 시에는 description 값을 응답할 예정

[feature/create-progress-status] 진행 상태를 관리하는 enum 객체 생성

---

src/main/java/com/example/demo/dto/milestone/request/MilestoneCreateRequestDto.java
src/main/java/com/example/demo/dto/milestone/response/MilestoneCreateResponseDto.java
src/main/java/com/example/demo/dto/milestone/response/MilestoneReadResponseDto.java
src/main/java/com/example/demo/model/milestone/Milestone.java

- 기존 마일스톤 엔티티의 expired_date, complete_date 필드를 삭제하고 ProgressStatus 타입의 progressStatus 필드 추가
- 마일스톤 엔티티의 필드가 변경됨에 따라 오류 발생 코드 수정

[feature/milestone-field-modify] 마일스톤 엔티티 필드 수정

---

src/main/java/com/example/demo/constant/ProgressStatus.java

- 요청한 코드 번호와 일치하는 ProgressStatus 데이터를 찾아 조회하는 로직 추가

[feature/find-progress-status] ProgressStatus 조회 로직 추가

---

src/main/java/com/example/demo/dto/milestone/request/MileStoneUpdateRequestDto.java
src/main/java/com/example/demo/model/milestone/Milestone.java

- 요구사항 변경으로 마일스톤 수정 요청 시 마일스톤의 진행 상태도 수정할수 있도록 MilestoneUpdateRequestDto에 진행 상태 코드 필드 추가
- 기존 마일스톤을 수정하는 로직에 요청한 진행 상태 코드를 검증하고 진행 상태를 수정하는 코드 추가

[feature/fix-milestone-update] 마일스톤 수정 로직 수정

---

src/main/java/com/example/demo/constant/ProgressStatus.java

- 요청한 code 값의 ProgressStatus를 조회하는 로직에서 없는 경우 null을 반환하지 않고 커스텀 예외를 처리하도록 수정

[feature/add-exception-handling-for-progress-status-code-lookup] ProgressStatus 조회 로직에 예외처리 추가

---

src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/dto/project/response/ProjectSpecificDetailResponseDto.java
src/main/java/com/example/demo/service/project/ProjectMemberService.java
src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java

- Response DTO에 사용자 권한 관련 Map 추가
- 사용자 권한 조회하는 메서드 생성
- Controller에 메서드 활용 후 Response DTO 설정

[feat/return-user-auth] feat : 사용자 권한 정보 반환

---

src/main/java/com/example/demo/dto/board/Response/BoardDetailResponseDto.java

- BoardDetailResponseDto의 completeStatus 필드 오타 수정

[feature/refactor-board-detail-response-dto] 게시글 상세 정보 응답 DTO 오타 수정

---

src/main/java/com/example/demo/controller/work/WorkController.java

- WorkController의 업무 삭제 요청 api의 메소드명 update -> delete로 변경

[feature/rename-work-delete] 업무 삭제 요청 메소드명 변경

---

src/main/java/com/example/demo/global/config/CorsConfig.java

- 클라이언트측에서 Authorization 헤더에 접근하지 못하는 이슈가 발생해 CorsConfig에서 addExposedHeader() 메소드로 클라이언트에 노출시킬 헤더 정보를 추가해 접근 가능하도록 수정

[feature/fix-cors-config] Cors 설정 수정

---

src/main/java/com/example/demo/security/custom/UserAuthenticationSuccessHandler.java

- 엑세스 토큰 값 앞에 "Bearer " 문자열을 붙여 응답하는 형태에서 엑세스 토큰 값만을 응답하도록 수정

[feature/refactor-login-success] 로그인 성공 시 엑세스 토큰 응답 형태 수정

---

.github/workflows/cicd.yml
appspec.yml
scripts/start.sh
scripts/stop.sh

- 젠킨스를 사용해 CICD를 구축하던 방법에서 Github Actions를 사용해 구축하는 방법으로 변경
- .github > workflows > cicd.yml 설정으로 cicd 자동화 설정
- appspec.yml 설정으로 배포환경의 Code Deploy가 수행할 작업 설정
- scripts > start.sh, stop.sh 설정으로 배포환경에서 애플리케이션 서버를 제어하는 작업 설정

[feature/gihub-actions] cicd를 위한 github actions 적용

---

src/main/resources/data.sql
src/main/resources/schema.sql

- 기술스택 테이블 기본 셋팅 데이터 수정
- 기술스택 카테고리 테이블 기본 셋팅 데이터 수정
- 기술스택, 기술스택 카테고리 중간 테이블 기본 셋팅 데이터 추가
#268

[feature/268-fix-technology-stack-data] 기술스택 관련 셋팅 데이터 수정

---

src/main/java/com/example/demo/controller/technology_stack/TechnologyStackCategoryController.java
src/main/java/com/example/demo/dto/technology_stack/response/TechnologyStackCategoryInfoResponseDto.java
src/main/java/com/example/demo/repository/technology_stack/TechnologyStackCategoryRepository.java
src/main/java/com/example/demo/service/technology_stack/TechnologyStackCategoryService.java
src/main/java/com/example/demo/service/technology_stack/TechnologyStackCategoryServiceImpl.java

- 기술스택 카테고리 Controller, Service, Repository 추가
- 기술스택 카테고리 목록을 조회하는 로직 추가
- 기술스택 카테고리 정보를 응답하는 TechnologyStackCategoryInfoResponseDto 추가
#268

[feature/268-feat-get-technology-stack-category-list] 기술스택 카테고리 목록 조회 로직 추가

---

src/main/java/com/example/demo/controller/trust_grade/TrustGradeController.java
src/main/java/com/example/demo/repository/trust_grade/TrustGradeRepositoryCustom.java
src/main/java/com/example/demo/repository/trust_grade/TrustGradeRepositoryImpl.java
src/main/java/com/example/demo/service/trust_grade/TrustGradeService.java
src/main/java/com/example/demo/service/trust_grade/TrustGradeServiceImpl.java
src/test/java/com/example/demo/trust_grade/service/TrustGradeServiceTest.java

요청에 의해,
회원에 따른 지원 가능한 신뢰등급을 조회하는 기능을 구현하였습니다.

[feat/read-user-grade] feat : 회원 지원 가능 등급 조회

---

src/main/java/com/example/demo/security/jwt/JsonWebTokenReissueFilter.java

저번에 로그인 시 프론트 브라우저에 쿠키 설정할 수 있도록 Refresh Token 설정하는 부분은 바꿨는데,
재발급 부분은 바꾸지 않아서 수정해서 올립니다.
토큰 재발급 과정에서 Bearer 제거 및 sameSite None 설정 등

fix: modify refresh token update logic

---

src/main/java/com/example/demo/controller/trust_grade/TrustGradeController.java
src/main/java/com/example/demo/repository/trust_grade/TrustGradeRepositoryImpl.java
src/test/java/com/example/demo/trust_grade/service/TrustGradeServiceTest.java

기존 사용자 별 지원/생성 가능한 신뢰등급 리스트 가져오는 조건이 잘못되어 변경하였습니다.
Notion 도 변경했습니다.

fix: change the criteria for getting a list of trust-grade by user

---

src/main/java/com/example/demo/repository/work/WorkRepositoryImpl.java

- 조건에 맞는 업무 개수 조회 쿼리 로직을 재사용 가능하도록 수정
- 조건을 구분하여 동적쿼리 적용

[feature/fix-work-total-count] 업무 개수 조회 쿼리 수정

---

src/main/java/com/example/demo/controller/board/BoardController.java
src/main/java/com/example/demo/controller/project/ProjectController.java
src/main/java/com/example/demo/dto/board/response/BoardSearchPaginationResponseDto.java
src/main/java/com/example/demo/repository/board/BoardRepositoryCustom.java
src/main/java/com/example/demo/repository/board/BoardRepositoryCustomImpl.java
src/main/java/com/example/demo/service/board/BoardService.java
src/main/java/com/example/demo/service/board/BoardServiceImpl.java

- 게시글 전체 검색 조회 전체 개수 조회 로직 변경 및 페이지 size 변경
- 포지션 참여 요청 후 성공 메세지 수정
제가 요청 드린거 그냥 제가 했습니다.
말씀드리고 싶은 부분은 원래 정렬을 updateDate 기준으로 하려고 했는데 조회수 오를 때마다 updateDate 가 변경되더라구요.. 그래서 임시로 createDate 로 했습니다.
close #313

게시글 전체 검색 조회 전체 개수 조회 로직 변경 및 페이지 size 변경

---

src/main/java/com/example/demo/dto/common/PaginationResponseDto.java

- PaginationResponseDto content 필드의 List 제네릭 타입을 T 클래스 타입으로 수정

[feature/fix-pagination-response-dto] 공통 페이징 처리 응답 DTO 수정

---

Dockerfile

- 도커 이미지를 빌드하기 위한 Dockerfile 스크립트 파일 생성
- 프로젝트 JAR 파일을 도커 이미지로 빌드하는 스크립트 추가

[feature/add-dockerfile-config] Dockerfile 스크립트 파일 추가

---

.github/workflows/gradle.yml

- 도커 컨테이너를 실행하는 스크립트에 작업 디렉토리 경로를 -v 옵션으로 매핑하도록 수정

[feature/fix-workflow-gradle.yml] gradle.yml 워크플로우 수정

---

.github/workflows/gradle.yml
.gitignore
Dockerfile

- 배포서버에서 스프링 서버 컨테이너가 실행될 때 호스트 환경변수를 불러오지 못하는 이슈로 .env 파일 추가
- 도커 이미지가 빌드되고 생성될 때 .env 파일도 함께 내부에 복사되도록 수정
- 배포환경에서 스프링 서버 컨테이너 실행 시 복사된 .env 파일을 참조하도록 수정

[feature/deploy-env-variables] 배포환경에서의 환경변수 설정

---

.github/workflows/gradle.yml

- Actions 실행 시 github Actions Secrets에 있는 정보로 application-prod.propertiec 파일을 생성하고 배포환경에서 스프링 서버가 실행될 때 application-prod.properties 파일이 application.properties 파일을 대체하도록 수정

[feature/add-application-prod-properties] 배포환경용 application-prod.propertice 적용

---

src/main/java/com/example/demo/service/alert/AlertService.java

- 코드를 병합하면서 AlertService의 findAlertsByProjectId() 메소드에서 누락된 반환 타입과 매개변수 수정

[feature/fix-build-alert-error] 빌드 시 alert 관련 에러 해결

---

src/main/java/com/example/demo/controller/board/BoardController.java

게시글 생성/수정/삭제 성공 시 메세지 수정

---

src/main/java/com/example/demo/model/work/Work.java

- Work(업무) 엔티티에서 User 엔티티와 매핑된 assignedUser 필드와 ProjectMember 엔티티와 매핑된 lastModifiedMember 필드의 연관관계를 `@ManyToOne` 으로 수정

[feature/fix-work-entity] 업무 엔티티 수정

---

src/main/java/com/example/demo/service/project/ProjectFacade.java

- 프로젝트 참여 컨펌 로직에 참여 수락 시 참여지원한 회원의 정보로 회원 프로젝트 이력을 등록하는 로직 추가

[feature/fix-project-participate-confirm]프로젝트 참여 컨펌 로직 수정

---

src/main/java/com/example/demo/service/project/ProjectFacade.java
src/main/java/com/example/demo/service/project/ProjectMemberFacade.java

- 프로젝트 참여 컨펌, 프로젝트 탈퇴 컨펌 로직에서 알림을 생성하는 로직 삭제

[feature/fix-notification-code] 컨펌 로직에서 알림 생성 코드 제거

---

src/main/java/com/example/demo/service/project/ProjectFacade.java
src/main/java/com/example/demo/service/project/ProjectMemberFacade.java

- merge된 feature/fix-notification-code 브랜치 변경사항 커밋 revert

[revert-feature/fix-notification-code] <feature/fix-notification-code> 브랜치 커밋 revert

---

src/main/java/com/example/demo/service/project/ProjectFacade.java

- 프로젝트 참여지원 로직에 `@Transactional` 어노태이션 추가

[feature/project-participate-add-transactional] 프로젝트 참여지원 로직 트랜잭션 추가

---

src/main/java/com/example/demo/controller/user/UserController.java
src/main/java/com/example/demo/service/user/UserFacade.java

로그인한 유저 외에 일반 사용자 id로 사용자 정보 조회하는 api가 급하게 필요해서 만들었습니다. 
바뀐 파일 : `UserController.java, UserFacade.java `
제가 가능하면 지금 작업 끝내고 싶어서 pr 확인 못하시는 상황이면 제가 force merge 하겠습니다.

feat: 사용자 정보 조회 컨트롤러/서비스 추가

---

src/main/java/com/example/demo/controller/project/ProjectMemberController.java
src/main/java/com/example/demo/model/project/Project.java
src/main/java/com/example/demo/service/project/ProjectMemberFacade.java
src/main/java/com/example/demo/service/project/ProjectMemberService.java
src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java

- feature/fix-project-member-forced-withdrawal 브랜치 병합사항 Revert

Revert "feature/fix-project-member-forced-withdrawal"

---

src/main/java/com/example/demo/service/project/ProjectMemberFacade.java

- 프로젝트 탈퇴 컨펌 요청 시 사용자 프로젝트 이력에 프로젝트 탈퇴 이력을 추가하도록 수정

[feature/fix-project-withdrawal-confirm] 프로젝트 탈퇴 컨펌 로직 수정

---

src/main/java/com/example/demo/service/project/ProjectFacade.java

- 프로젝트 종료 로직에서 프로젝트의 역할, 권한이 매니저인지 검증 시ProjectMemberService.verifiedProjectManager() 로직을 수행하도록 수정

[feature/fix-project-end-verified-manager] 프로젝트 종료 로직의 매니저 검증 로직 수정

---

src/main/java/com/example/demo/repository/work/WorkRepositoryImpl.java

- 기존 프로젝트, 마일스톤에 속한 업무목록 조회 로직에서 업무의 assignedUser 필드에 잘못된 데이터가 셋팅되어 응답되던 버그 수정
- 업무목록을 조회하는 쿼리에서 서브쿼리를 사용해 해당 업무 할당자의 projectMember.id를 따로 조회해 응답하도록 수정<br><br><br>
#403

[feature/403-fix-work-list] 프로젝트, 마일스톤에 속한 업무목록 조회 쿼리 수정

---

src/main/java/com/example/demo/service/project/ProjectFacade.java

- 참여중인 프로젝트 목록 조회 요청 시 요청할 수 있는 최대 itemCount 변경<br><br><br>
close #409

[feature/409-fix-participate-projects-item-count] 참여중인 프로젝트 목록 조회 요청 데이터 개수 수정

---

src/main/java/com/example/demo/service/user/UserFacade.java

- 회원탈퇴 시 해당 회원의 기술스택 목록을 함께 삭제하도록 수정

[feature/fix-user-withdrawal] 회원탈퇴 로직 수정

---

src/main/java/com/example/demo/service/trust_score/TrustScoreServiceImpl.java

- TrustScoreHistory 엔티티에 content 필드가 추가되어 TrustScoreHistory 데이터를 저장하는 로직에서 엔티티를 셋팅하는 코드에 content 필드도 함께 셋팅하도록 수정

[feature/fix-save-trust-score-history] 신뢰점수 이력 저장 로직 수정

---

src/main/java/com/example/demo/constant/ProjectMemberStatus.java

- 프로젝트 멤버의 상태 값 중 'WITHDRAWLING(탈퇴)' 데이터 삭제

[feature/fix-project-member-status] 프로젝트 멤버 상태 값 수정

---

src/main/java/com/example/demo/service/project/ProjectMemberFacade.java

- 프로젝트 멤버 강제탈퇴 시 해당 멤버 정보와 프로젝트 정보로 강제탈퇴 알림을 생성하고 저장하도록 수정

[feature/project-member-force-withdrawal-alert] 프로젝트 멤버 강제탈퇴 로직에 알림 생성 로직 추가

---

src/main/java/com/example/demo/controller/alert/AlertController.java
src/main/java/com/example/demo/controller/milestone/MileStoneController.java
src/main/java/com/example/demo/controller/trust_grade/TrustGradeController.java
src/main/java/com/example/demo/controller/trust_score/TrustScoreTypeController.java
src/main/java/com/example/demo/controller/work/WorkController.java

- 각 Controller의 매핑 URL 경로에서 공통 패턴 경로(/api/엔티티 명)를 `@RequestMapping` 어노테이션으로 분리해 공통으로 관리하도록 리팩토링

[refactor/url-pattern] 매핑 URL 패턴 리팩토링

---

src/main/java/com/example/demo/repository/alert/AlertRepository.java
src/main/java/com/example/demo/service/project/ProjectMemberService.java
src/main/java/com/example/demo/service/project/ProjectMemberServiceImpl.java
src/main/java/com/example/demo/service/user/UserProjectHistoryService.java
src/main/java/com/example/demo/service/user/UserProjectHistoryServiceImpl.java
src/main/java/com/example/demo/service/user/UserTechnologyStackService.java
src/main/java/com/example/demo/service/user/UserTechnologyStackServiceImpl.java

- 각 엔티티의 Repository, Service Layer에서 구현은 되어있지만 사용되지 않는 메소드 목록 삭제

[cleanup/remove-unused-methods] 사용되지 않는 매소드 목록 삭제 및 정리

---

.github/workflows/deploy-cicd.yml

- 실행중인 모든 도커 컨테이너를 중지하고 최근 빌드된 도커 이미지를 끌어와 docker-compose로 시작하고 사용되지 않는 도커 이미지를 삭제하는 과정으로 배포 스크립트 수정

fix : ec2 배포 스크립트 수정

---

.github/workflows/deploy-cicd.yml

- ca85d821623171d4e16e7f7da6a48435533d0344 커밋 revert
-

Revert "fix : ec2 배포 스크립트 수정"

---

.github/workflows/deploy-cicd.yml

- ci cd 배포 스크립트에서 docker-compose 관련 스크립트에 -f 옵션을 사용해 docker-compose.yml 경로 지정하도록 수정
-

fix : ci cd 배포 스크립트에서 docker-compose 스크립트 수정

---

.github/workflows/deploy-cicd.yml

- 44332d9064b02fea476da27ad445df88b8313734 커밋 revert
-

Revert "fix : ci cd 배포 스크립트에서 docker-compose 스크립트 수정"

---

.github/workflows/deploy-cicd.yml

- ci cd 배포 스크립트에 docker-compose.yml 경로를 환경변수로 등록하고 스크립트에 적용
-

fix : ci cd 배포 스크립트 수정

---

.github/workflows/deploy-cicd.yml

- 8932a98ca5c9f008e4945495a641428aa55700f2 커밋 revert
-

Revert "fix : ci cd 배포 스크립트 수정"

---

.github/workflows/deploy-cicd.yml

- ci cd deploy 작업에서 docker-compose up 명령에 -f 절대 경로 옵션을 추가해 docker-compose.yml 파일의 경로를 지정하도록 수정
-

fix : docker-compose up 스크립트 수정

---

.github/workflows/deploy-cicd.yml

- d0f54e6fe21823fc9c694f724a6b72a5b0c0f3a1 커밋 revert
-

Revert "fix : docker-compose up 스크립트 수정"

---

.github/workflows/deploy-cicd.yml

- cicd deploy 스크립트 중 docker-compose up 스크립트에 -f 절대 경로 옵션을 추가해 파일의 경로를 지정하도록 수정
-

fix : cicd deploy docker-compose 스크립트 수정
